<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CategoryDataCenterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
            \DB::table('category_data_centers')->insert([
                [
                    'id' => 1,
                    'name' => 'Rencana Pembangunan Jangka Panjang Nasional (RPJPN)',
                    'created_at' => '2020-11-29 02:34:10',
                    'updated_at' => '2021-10-26 00:22:18',
                    'order' => 1,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 2,
                    'name' => 'Rencana Pembangunan Jangka Menengah Nasional (RPJMN)',
                    'created_at' => '2020-11-29 02:34:55',
                    'updated_at' => '2021-10-26 00:22:39',
                    'order' => 2,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 3,
                    'name' => 'Rencana Pembangunan Jangka Panjang Daerah (RPJPD)',
                    'created_at' => '2020-11-29 02:37:18',
                    'updated_at' => '2021-10-26 00:23:19',
                    'order' => 3,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 4,
                    'name' => 'Rencana Pembangunan Jangka Menengah Daerah (RPJMD)',
                    'created_at' => '2021-01-10 02:03:05',
                    'updated_at' => '2021-10-26 00:23:49',
                    'order' => 4,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 5,
                    'name' => 'Rencana Kerja Pemerintah (RKP)',
                    'created_at' => '2020-11-29 02:36:42',
                    'updated_at' => '2021-10-26 00:22:51',
                    'order' => 5,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 6,
                    'name' => 'Rencana Pembangunan Daerah (RPD)',
                    'created_at' => '2023-03-01 10:27:12',
                    'updated_at' => '2023-03-01 13:29:52',
                    'order' => 6,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 7,
                    'name' => 'Rencana Tindak Pengendalian (RTP)',
                    'created_at' => '2023-01-10 08:57:10',
                    'updated_at' => '2023-01-10 08:57:10',
                    'order' => 7,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 8,
                    'name' => 'Rencana Kerja Tahunan (RKT)',
                    'created_at' => '2024-05-06 03:32:14',
                    'updated_at' => '2024-05-06 03:32:34',
                    'order' => 8,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 9,
                    'name' => 'Rencana Strategis (Renstra) Provinsi Kalimantan Timur Tahun 2024-2026',
                    'created_at' => '2024-09-23 07:05:06',
                    'updated_at' => '2024-09-23 07:46:37',
                    'order' => 9,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 10,
                    'name' => 'Rencana Strategis (Renstra)',
                    'created_at' => '2021-01-10 02:12:24',
                    'updated_at' => '2021-10-26 00:24:41',
                    'order' => 10,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 11,
                    'name' => 'Rencana Kerja (Renja)',
                    'created_at' => '2021-01-10 02:12:06',
                    'updated_at' => '2021-10-26 00:26:26',
                    'order' => 11,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 12,
                    'name' => 'Rencana Kerja Pemerintah Daerah (RKPD)',
                    'created_at' => '2021-01-10 02:02:44',
                    'updated_at' => '2021-10-26 00:25:35',
                    'order' => 12,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 13,
                    'name' => 'Perjanjian Kinerja (PK)',
                    'created_at' => '2021-01-10 02:13:03',
                    'updated_at' => '2021-10-26 00:34:09',
                    'order' => 13,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 14,
                    'name' => 'Laporan Analisis Ketimpangan Wilayah',
                    'created_at' => '2023-01-10 08:57:10',
                    'updated_at' => '2023-01-10 08:57:10',
                    'order' => 14,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 15,
                    'name' => 'Dokumen Pelaksanaan Anggaran (DPA)',
                    'created_at' => '2021-10-26 00:33:52',
                    'updated_at' => '2022-12-06 07:30:19',
                    'order' => 15,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 16,
                    'name' => 'Indikator Kinerja Utama (IKU)',
                    'created_at' => '2021-01-10 04:49:19',
                    'updated_at' => '2021-10-26 00:34:12',
                    'order' => 16,
                    'slug' => Str::slug(Str::random(5)),
                ],

                [
                    'id' => 17,
                    'name' => 'Rencana Tata Ruang Wilayah (RTRW)',
                    'created_at' => '2021-01-10 00:19:24',
                    'updated_at' => '2021-10-26 00:34:07',
                    'order' => 17,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 18,
                    'name' => 'Laporan Kinerja Instansi Pemerintah (LKjIP)',
                    'created_at' => '2021-08-29 22:55:00',
                    'updated_at' => '2021-10-27 00:45:15',
                    'order' => 18,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 19,
                    'name' => 'Laporan Keterangan Pertanggungjawaban (LKPJ)',
                    'created_at' => '2021-10-26 01:03:00',
                    'updated_at' => '2021-10-27 00:45:18',
                    'order' => 19,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 20,
                    'name' => 'Evaluasi Rencana Pembangunan Jangka Menengah Daerah (RPJMD)',
                    'created_at' => '2021-10-27 00:45:00',
                    'updated_at' => '2022-12-06 07:37:32',
                    'order' => 20,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 21,
                    'name' => 'Evaluasi Rencana Kerja Pemerintah Daerah (RKPD)',
                    'created_at' => '2021-10-27 00:46:00',
                    'updated_at' => '2022-12-26 08:17:20',
                    'order' => 21,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 22,
                    'name' => 'Laporan Evaluasi dan Pengawasan Anggaran Kaltim',
                    'created_at' => '2021-10-27 19:54:00',
                    'updated_at' => '2021-10-30 16:16:10',
                    'order' => 22,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 23,
                    'name' => 'Laporan Kinerja Perekonomian',
                    'created_at' => '2022-05-24 05:38:32',
                    'updated_at' => '2022-05-24 05:38:32',
                    'order' => 23,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 24,
                    'name' => 'Data Dukung My SAPK-PDM',
                    'created_at' => '2021-08-15 19:46:00',
                    'updated_at' => '2022-12-06 06:37:38',
                    'order' => 24,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 25,
                    'name' => 'Ibu Kota Negara',
                    'created_at' => '2021-09-29 20:41:00',
                    'updated_at' => '2022-12-06 06:40:05',
                    'order' => 25,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 26,
                    'name' => 'Dasar Peraturan',
                    'created_at' => '2021-10-26 00:49:00',
                    'updated_at' => '2022-12-06 06:40:39',
                    'order' => 26,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 27,
                    'name' => 'Standar Operasional Prosedur (SOP)',
                    'created_at' => '2021-10-27 22:33:00',
                    'updated_at' => '2022-03-27 10:49:19',
                    'order' => 27,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 28,
                    'name' => 'Maklumat Pelayanan',
                    'created_at' => '2021-10-28 08:16:00',
                    'updated_at' => '2022-12-06 06:39:04',
                    'order' => 28,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 29,
                    'name' => 'Laporan',
                    'created_at' => '2021-10-28 08:28:00',
                    'updated_at' => '2022-12-06 06:40:01',
                    'order' => 29,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 30,
                    'name' => 'Prosedur',
                    'created_at' => '2021-10-28 08:28:00',
                    'updated_at' => '2022-12-06 06:40:07',
                    'order' => 30,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 31,
                    'name' => 'Survey Kepuasan Masyarakat (SKM)',
                    'created_at' => '2021-10-29 07:31:00',
                    'updated_at' => '2022-12-06 06:39:07',
                    'order' => 31,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 32,
                    'name' => 'PPID Bappeda Provinsi Kalimantan Timur',
                    'created_at' => '2021-10-30 13:13:00',
                    'updated_at' => '2022-12-06 06:39:39',
                    'order' => 32,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 33,
                    'name' => 'Formulir Permohonan Informasi dan Keberatan Informasi',
                    'created_at' => '2021-10-30 15:36:00',
                    'updated_at' => '2023-02-27 01:45:58',
                    'order' => 33,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 34,
                    'name' => 'Daftar Informasi Yang Dikecualikan',
                    'created_at' => '2021-10-30 17:33:00',
                    'updated_at' => '2022-12-06 06:38:36',
                    'order' => 34,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 35,
                    'name' => 'Kaltim Dalam Angka (Data BPS)',
                    'created_at' => '2021-10-31 01:57:00',
                    'updated_at' => '2022-12-06 06:37:55',
                    'order' => 35,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 36,
                    'name' => 'Laporan Perekonomian Provinsi Kalimantan Timur',
                    'created_at' => '2021-10-31 03:14:00',
                    'updated_at' => '2023-01-10 08:56:13',
                    'order' => 36,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 37,
                    'name' => 'TPB/SDGs Kalimantan Timur',
                    'created_at' => '2021-12-17 12:18:00',
                    'updated_at' => '2023-02-06 12:45:05',
                    'order' => 37,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 38,
                    'name' => 'Laporan Resume Pengadaan Barang Jasa',
                    'created_at' => '2022-03-17 04:54:00',
                    'updated_at' => '2022-12-06 06:39:36',
                    'order' => 38,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 39,
                    'name' => 'Standar Pelayanan (SP)',
                    'created_at' => '2022-03-27 10:43:00',
                    'updated_at' => '2022-12-06 06:37:46',
                    'order' => 39,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 40,
                    'name' => 'Buku Panduan Sistem Analisis Data Perencanaan Pembangunan (SADAP)',
                    'created_at' => '2022-12-02 04:17:00',
                    'updated_at' => '2023-01-10 08:56:29',
                    'order' => 40,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 41,
                    'name' => 'Analisis Jabatan (ANJAB) dan Analisis Beban Kerja (ABK)',
                    'created_at' => '2022-12-06 06:50:00',
                    'updated_at' => '2023-01-10 08:56:17',
                    'order' => 41,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 42,
                    'name' => 'Laporan Analisis Ketimpangan Wilayah',
                    'created_at' => '2023-01-10 08:57:10',
                    'updated_at' => '2023-01-10 08:57:10',
                    'order' => 42,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 43,
                    'name' => 'Laporan Permohonan Informasi Tahun 2024',
                    'created_at' => '2023-01-10 08:57:10',
                    'updated_at' => '2023-01-10 08:57:10',
                    'order' => 43,
                    'slug' => Str::slug(Str::random(5)),
                ],
                [
                    'id' => 44,
                    'name' => 'Laporan Permohonan Informasi Tahun 2024',
                    'created_at' => '2023-01-10 08:57:10',
                    'updated_at' => '2023-01-10 08:57:10',
                    'order' => 44,
                    'slug' => Str::slug(Str::random(5)),
                ],
            ]);
    }
}
