<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DataCenterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('data_centers')->insert([
                [
                    'id' => 21,
                    'name' => 'BUKU PETUNJUK USER PDM V.1',
                    'file' => ' ',
                    'created_at' => '2021-08-15 19:48:33',
                    'updated_at' => '2021-08-15 19:48:33',
                    'category_data_center_id' => 7,
                    'order' => NULL,
                    'slug' => Str::slug('BUKU PETUNJUK USER PDM V.1'),
                ],
                [
                    'id' => 22,
                    'name' => 'JADWAL PDM',
                    'file' => 'wJy1AbfoEfVznl989ZP6.pdf',
                    'created_at' => '2021-08-15 19:49:53',
                    'updated_at' => '2021-08-15 19:49:53',
                    'category_data_center_id' => 7,
                    'order' => NULL,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 23,
                    'name' => 'DOKUMEN PENGGANTI USUL PDM',
                    'file' => '0ttQkuWXrdapXNFYd6Ph.jpeg',
                    'created_at' => '2021-08-15 19:51:09',
                    'updated_at' => '2021-08-15 19:51:09',
                    'category_data_center_id' => 7,
                    'order' => NULL,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 24,
                    'name' => 'DOKUMEN YANG DIUPLOAD PDM',
                    'file' => 'tQs6i7ajTkaC3vgDJHrw.jpeg',
                    'created_at' => '2021-08-15 19:51:31',
                    'updated_at' => '2021-08-15 19:51:31',
                    'category_data_center_id' => 7,
                    'order' => NULL,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 25,
                    'name' => 'TARGET PENDATAAN PDM',
                    'file' => 'hM8W3AB74TMf44UVQGag.jpeg',
                    'created_at' => '2021-08-15 19:51:54',
                    'updated_at' => '2021-08-15 19:51:54',
                    'category_data_center_id' => 7,
                    'order' => NULL,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 26,
                    'name' => 'UPDATE DATA MANDIRI',
                    'file' => 'CEazgbj0f3npqBl6uvO1.jpeg',
                    'created_at' => '2021-08-15 19:53:33',
                    'updated_at' => '2021-08-15 19:54:46',
                    'category_data_center_id' => 7,
                    'order' => NULL,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 27,
                    'name' => 'Naskah Akademik RUU IKN',
                    'file' => 'zNPFAwFfhrKe6NOUadXI.pdf',
                    'created_at' => '2021-09-29 20:42:50',
                    'updated_at' => '2021-09-29 20:43:23',
                    'category_data_center_id' => 8,
                    'order' => 2,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 28,
                    'name' => 'RUU IKN dan Penjelasan',
                    'file' => 'CTWx79HXWVUwxTQ1buAa.pdf',
                    'created_at' => '2021-09-29 20:43:17',
                    'updated_at' => '2021-09-29 20:43:28',
                    'category_data_center_id' => 8,
                    'order' => 1,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 31,
                    'name' => 'UU Nomor 23 Tahun 2014 Tentang Pemerintah Daerah',
                    'file' => 'lqGqVzonDNblnqWwyS3r.pdf',
                    'created_at' => '2021-10-27 00:14:34',
                    'updated_at' => '2022-02-21 03:22:21',
                    'category_data_center_id' => 9,
                    'order' => 100,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 32,
                    'name' => 'UU Nomor 25 Tahun 2004 Tentang Sistem Perencanaan Pembangunan Nasional',
                    'file' => 'UU Nomor 25 Tahun 2004.pdf',
                    'created_at' => '2021-10-27 00:15:38',
                    'updated_at' => '2022-02-21 03:22:10',
                    'category_data_center_id' => 9,
                    'order' => 99,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 33,
                    'name' => 'Permendagri Nomor 86 Tahun 2017',
                    'file' => 'Permendagri Nomor 86 Tahun 2017.pdf',
                    'created_at' => '2021-10-27 00:18:19',
                    'updated_at' => '2021-10-28 08:24:34',
                    'category_data_center_id' => 9,
                    'order' => 97,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 34,
                    'name' => 'Permendagri Nomor 99 Tahun 2019 Tentang Perubahan Kelima Atas Peraturan Menteri Dalam Negeri Nomor 32 Tahun 2011 Tentang Pedoman Pemberian Hibah Dan Bantuan Sosial Yang Bersumber Dari Anggaran Pendapatan Dan Belanja Daerah',
                    'file' => 'Permendagri Nomor 99 Tahun 2019.pdf',
                    'created_at' => '2021-10-27 00:20:58',
                    'updated_at' => '2022-02-21 03:20:01',
                    'category_data_center_id' => 9,
                    'order' => 98,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 35,
                    'name' => 'Perda Nomor 2 Tahun 2019 Tentang Rencana Pembangunan Jangka Menengah Daerah Provinsi Kalimantan Timur Tahun 2019--2023',
                    'file' => 'Perda Nomor 2 Tahun 2019.pdf',
                    'created_at' => '2021-10-27 00:25:24',
                    'updated_at' => '2022-02-21 03:18:28',
                    'category_data_center_id' => 9,
                    'order' => 96,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 36,
                    'name' => 'Perda Nomor 7 Tahun 2014 Tentang Rencana Pembangunan Jangka Menengah Daerah Provinsi Kalimantan Timur Tahun 2013-2018',
                    'file' => 'Perda Nomor 7 Tahun 2014.pdf',
                    'created_at' => '2021-10-27 00:26:04',
                    'updated_at' => '2022-02-21 03:17:43',
                    'category_data_center_id' => 9,
                    'order' => 95,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 37,
                    'name' => 'Perda Nomor 4 Tahun 2009 Tentang Rencana Pembangunan Jangka Menengah Daerah Provinsi Kalimantan Timur Tahun 2009-2013',
                    'file' => 'Perda Nomor 4 Tahun 2009.pdf',
                    'created_at' => '2021-10-27 00:28:32',
                    'updated_at' => '2022-02-21 03:17:00',
                    'category_data_center_id' => 9,
                    'order' => 94,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 38,
                    'name' => 'Pergub Nomor 25 Tahun 2021 Tentang Rencana Kerja Pemerintah Daerah Provinsi Kalimantan Timur Tahun 2022',
                    'file' => 'Pergub Nomor 25 Tahun 2021.pdf',
                    'created_at' => '2021-10-27 00:30:07',
                    'updated_at' => '2022-12-06 08:03:00',
                    'category_data_center_id' => 9,
                    'order' => 92,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 39,
                    'name' => 'Pergub Nomor 42 Tahun 2020 Tentang Rencana Kerja Pemerintah Daerah Provinsi Kalimantan Timur Tahun 2021',
                    'file' => 'Pergub Nomor 42 Tahun 2020.pdf',
                    'created_at' => '2021-10-27 00:31:09',
                    'updated_at' => '2022-12-06 08:03:02',
                    'category_data_center_id' => 9,
                    'order' => 91,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 40,
                    'name' => 'Pergub Nomor 25 Tahun 2018 Tentang Perubahan Peraturan Gubernur Kalimantan Timur Nomor 20 Tahun 2017 Tentang Rencana Kerja Pemerintah Daerah Provinsi Kalimantan Timur Tahun 2018',
                    'file' => 'Pergub Nomor 25 Tahun 2018.pdf',
                    'created_at' => '2021-10-27 00:31:55',
                    'updated_at' => '2022-12-06 08:03:05',
                    'category_data_center_id' => 9,
                    'order' => 90,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 41,
                    'name' => 'Pergub Nomor 18 Tahun 2018 Tentang Rencana Kerja Pemerintah Daerah Provinsi Kalimantan Timur Tahun 2019',
                    'file' => 'Pergub Nomor 18 Tahun 2018.pdf',
                    'created_at' => '2021-10-27 00:34:04',
                    'updated_at' => '2022-12-06 08:03:07',
                    'category_data_center_id' => 9,
                    'order' => 89,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 42,
                    'name' => 'Pergub Nomor 33 Tahun 2011 Tentang Rencana Kerja Pembangunan Daerah (RKPD) Provinsi Kalimantan Timur Tahun 2012',
                    'file' => 'Pergub Nomor 33 Tahun 2011.pdf',
                    'created_at' => '2021-10-27 00:34:52',
                    'updated_at' => '2022-12-06 08:03:09',
                    'category_data_center_id' => 9,
                    'order' => 88,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 43,
                    'name' => 'Pergub Nomor 22 Tahun 2008 Tentang Rencana Kerja Pemerintah Daerah (RKPD) Provinsi Kalimantan Timur Tahun 2009',
                    'file' => 'Pergub Nomor 22 Tahun 2008.pdf',
                    'created_at' => '2021-10-27 00:35:25',
                    'updated_at' => '2022-12-06 08:03:11',
                    'category_data_center_id' => 9,
                    'order' => 87,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 45,
                    'name' => 'SOP Bappeda Tahun 2021 Final',
                    'file' => 'SOP BAPPEDA TAHUN 2021_compressed.pdf',
                    'created_at' => '2021-10-27 23:01:10',
                    'updated_at' => '2022-03-27 10:41:03',
                    'category_data_center_id' => 11,
                    'order' => 1,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 46,
                    'name' => 'MAKLUMAT PELAYANAN BAPPEDA KALTIM',
                    'file' => 'MAKLUMAT PELAYANAN BAPPEDA KALTIM.docx',
                    'created_at' => '2021-10-28 08:16:50',
                    'updated_at' => '2021-10-28 08:16:50',
                    'category_data_center_id' => 12,
                    'order' => 1,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 47,
                    'name' => 'Laporan Akses Informasi Publik 2021',
                    'file' => 'Laporan Akses Informasi Publik 2021.pdf',
                    'created_at' => '2021-10-29 04:50:53',
                    'updated_at' => '2023-02-01 04:43:16',
                    'category_data_center_id' => 13,
                    'order' => 5,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 50,
                    'name' => 'Laporan Realisasi Anggaran Bappeda 2019',
                    'file' => 'Laporan Realisasi Anggaran Bappeda 2019.pdf',
                    'created_at' => '2021-10-29 04:52:50',
                    'updated_at' => '2023-02-01 04:41:37',
                    'category_data_center_id' => 13,
                    'order' => 2,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 52,
                    'name' => 'Prosedur Pengajuan Keberatan',
                    'file' => 'PENGAJU KEBERATAN.docx',
                    'created_at' => '2021-10-29 04:57:32',
                    'updated_at' => '2021-10-30 16:11:00',
                    'category_data_center_id' => 14,
                    'order' => 2,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 53,
                    'name' => 'Prosedur Sengketa Informasi',
                    'file' => 'PROSEDUR PENGAJUAN SENGKETA INFORMASI.docx',
                    'created_at' => '2021-10-29 04:58:36',
                    'updated_at' => '2021-10-30 16:49:36',
                    'category_data_center_id' => 14,
                    'order' => 3,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 51,
                    'name' => 'Prosedur Permohonan Informasi',
                    'file' => 'PROSEDUR PERMOHONAN.docx',
                    'created_at' => '2021-10-29 04:56:51',
                    'updated_at' => '2021-10-30 16:11:52',
                    'category_data_center_id' => 14,
                    'order' => 1,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 54,
                    'name' => 'Laporan Realisasi Anggaran Bappeda 2018',
                    'file' => 'Laporan Realisasi Anggaran Bappeda 2018.pdf',
                    'created_at' => '2021-10-29 06:55:15',
                    'updated_at' => '2023-02-01 04:41:35',
                    'category_data_center_id' => 13,
                    'order' => 1,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 55,
                    'name' => 'Laporan Realisasi Anggaran Bappeda 2020',
                    'file' => 'Laporan Realisasi Anggaran Bappeda 2020.pdf',
                    'created_at' => '2021-10-29 07:00:24',
                    'updated_at' => '2023-02-01 04:41:39',
                    'category_data_center_id' => 13,
                    'order' => 3,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 56,
                    'name' => 'Laporan Realisasi Anggaran Bappeda 2021',
                    'file' => 'Laporan Realisasi Anggaran Bappeda 2021.pdf',
                    'created_at' => '2021-10-29 07:00:53',
                    'updated_at' => '2023-02-01 04:41:41',
                    'category_data_center_id' => 13,
                    'order' => 4,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 57,
                    'name' => 'Survey Kepuasan Masyarakat tahun 2020',
                    'file' => 'SURVEI KEPUASAN MASYARAKAT TAHUN 2020_compressed.pdf',
                    'created_at' => '2021-10-29 07:33:15',
                    'updated_at' => '2021-11-01 05:28:23',
                    'category_data_center_id' => 15,
                    'order' => 1,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 58,
                    'name' => 'SK PPID Bappeda Tahun 2021',
                    'file' => 'SK PPID Tahun 2021.docx',
                    'created_at' => '2021-10-30 15:39:36',
                    'updated_at' => '2022-01-31 03:49:09',
                    'category_data_center_id' => 16,
                    'order' => 2,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 59,
                    'name' => 'Formulir Permohonan Informasi Bappeda',
                    'file' => 'Formulir Permohonan Informasi Bappeda Kaltim.docx',
                    'created_at' => '2021-10-30 15:40:14',
                    'updated_at' => '2022-08-01 03:51:06',
                    'category_data_center_id' => 17,
                    'order' => 1,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 60,
                    'name' => 'SK Humas Bappeda 2020',
                    'file' => 'sk humas 2020.pdf',
                    'created_at' => '2021-10-30 16:30:24',
                    'updated_at' => '2021-10-30 16:30:24',
                    'category_data_center_id' => 16,
                    'order' => 1,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 61,
                    'name' => 'Daftar Informasi PPID Yang Dikecualikan tahun 2021',
                    'file' => 'Daftar Informasi PPID Yang Dikecualikan tahun 2021.pdf',
                    'created_at' => '2021-10-30 17:35:30',
                    'updated_at' => '2023-02-27 02:01:59',
                    'category_data_center_id' => 18,
                    'order' => 1,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 62,
                    'name' => 'Kaltim Dalam Angka Tahun 2021 (BPS Kaltim)',
                    'file' => 'Provinsi Kalimantan Timur Dalam Angka 2021.pdf',
                    'created_at' => '2021-10-31 01:59:05',
                    'updated_at' => '2023-01-16 06:52:20',
                    'category_data_center_id' => 19,
                    'order' => 3,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 63,
                    'name' => 'Kaltim Dalam Angka Tahun 2020 (BPS Kaltim)',
                    'file' => 'Provinsi Kalimantan Timur Dalam Angka 2020.pdf',
                    'created_at' => '2021-10-31 02:01:19',
                    'updated_at' => '2023-01-16 06:52:17',
                    'category_data_center_id' => 19,
                    'order' => 2,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 64,
                    'name' => 'Kaltim Dalam Angka Tahun 2019 (BPS Kaltim)',
                    'file' => 'Provinsi Kalimantan Timur Dalam Angka 2019.pdf',
                    'created_at' => '2021-10-31 02:11:31',
                    'updated_at' => '2023-01-16 06:51:58',
                    'category_data_center_id' => 19,
                    'order' => 1,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 65,
                    'name' => 'Laporan Perekonomian Provinsi Kaltim Agustus 2021 (Bank Indonesia)',
                    'file' => 'Laporan Perekonomian Provinsi Kalimantan Timur Agustus 2021.pdf',
                    'created_at' => '2021-10-31 03:18:49',
                    'updated_at' => '2023-01-10 08:36:18',
                    'category_data_center_id' => 20,
                    'order' => 11,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 66,
                    'name' => 'Laporan Perekonomian Provinsi Kaltim Mei 2021 (Bank Indonesia)',
                    'file' => 'Laporan Perekonomian Provinsi Kalimantan Timur Mei 2021.pdf',
                    'created_at' => '2021-10-31 03:19:57',
                    'updated_at' => '2023-01-10 08:35:52',
                    'category_data_center_id' => 20,
                    'order' => 10,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 67,
                    'name' => 'Laporan Perekonomian Provinsi Kaltim Februari 2021 (Bank Indonesia)',
                    'file' => 'Laporan Perekonomian Provinsi Kalimantan Timur Februari 2021.pdf',
                    'created_at' => '2021-10-31 03:21:10',
                    'updated_at' => '2023-01-10 08:35:49',
                    'category_data_center_id' => 20,
                    'order' => 9,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 68,
                    'name' => 'Laporan Perekonomian Provinsi Kaltim November 2020 (Bank Indonesia)',
                    'file' => 'Laporan Perekonomian Provinsi Kalimantan Timur November 2020.pdf',
                    'created_at' => '2021-10-31 03:22:11',
                    'updated_at' => '2023-01-10 08:34:53',
                    'category_data_center_id' => 20,
                    'order' => 8,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 69,
                    'name' => 'Laporan Perekonomian Provinsi Kaltim Agustus 2020 (Bank Indonesia)',
                    'file' => 'Laporan Perekonomian Provinsi Kalimantan Timur Agustus 2020.pdf',
                    'created_at' => '2021-10-31 03:22:49',
                    'updated_at' => '2023-01-10 08:34:51',
                    'category_data_center_id' => 20,
                    'order' => 7,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 70,
                    'name' => 'Laporan Perekonomian Provinsi Kaltim Mei 2020 (Bank Indonesia)',
                    'file' => 'Laporan Perekonomian Provinsi Kalimantan Timur Mei 2020.pdf',
                    'created_at' => '2021-10-31 03:23:39',
                    'updated_at' => '2021-10-31 03:23:39',
                    'category_data_center_id' => 20,
                    'order' => 6,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 71,
                    'name' => 'Laporan Perekonomian Provinsi Kaltim Februari 2020 (Bank Indonesia)',
                    'file' => 'Laporan Perekonomian Provinsi Kalimantan Timur Februari 2020.pdf',
                    'created_at' => '2021-10-31 03:24:20',
                    'updated_at' => '2023-01-10 08:34:32',
                    'category_data_center_id' => 20,
                    'order' => 5,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 72,
                    'name' => 'Laporan Perekonomian Provinsi Kaltim November 2019 (Bank Indonesia)',
                    'file' => 'Laporan Perekonomian Provinsi Kalimantan Timur Nov 2019.pdf',
                    'created_at' => '2021-10-31 03:25:07',
                    'updated_at' => '2023-01-10 08:34:17',
                    'category_data_center_id' => 20,
                    'order' => 4,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 73,
                    'name' => 'Laporan Perekonomian Provinsi Kaltim Agustus 2019 (Bank Indonesia)',
                    'file' => 'Laporan Perekonomian Provinsi Kalimantan Timur Aug 2019.pdf',
                    'created_at' => '2021-10-31 03:25:54',
                    'updated_at' => '2023-01-10 08:34:14',
                    'category_data_center_id' => 20,
                    'order' => 3,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 74,
                    'name' => 'Laporan Perekonomian Provinsi Kaltim Mei 2019 (Bank Indonesia)',
                    'file' => 'Laporan Perekonomian Provinsi Kalimantan Timur Mei 2019.pdf',
                    'created_at' => '2021-10-31 03:26:39',
                    'updated_at' => '2023-01-10 08:33:05',
                    'category_data_center_id' => 20,
                    'order' => 2,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 75,
                    'name' => 'Laporan Perekonomian Provinsi Kaltim Februari 2019 (Bank Indonesia)',
                    'file' => 'KEKR Provinsi Kalimantan Timur Februari 2019.pdf',
                    'created_at' => '2021-10-31 03:27:25',
                    'updated_at' => '2023-01-10 08:30:57',
                    'category_data_center_id' => 20,
                    'order' => 1,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 77,
                    'name' => 'LAPORAN SKM SEMESTER I TAHUN 2021',
                    'file' => 'LAPORAN SKM SEMESTER I TAHUN 2021.pdf',
                    'created_at' => '2021-10-31 05:45:25',
                    'updated_at' => '2022-01-06 02:42:09',
                    'category_data_center_id' => 15,
                    'order' => 2,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 78,
                    'name' => 'SOP Peliputan Humas Bappeda Kaltim',
                    'file' => 'SOP Peliputan Informasi dan Dokumentasi Bappeda Kaltim.xlsx',
                    'created_at' => '2021-10-31 06:07:47',
                    'updated_at' => '2021-10-31 06:07:47',
                    'category_data_center_id' => 16,
                    'order' => 3,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 79,
                    'name' => 'PP Nomor 94 Tahun 2021 Tentang Disiplin Pegawai Negeri Sipil',
                    'file' => 'PP Nomor 94 Tahun 2021_compressed.pdf',
                    'created_at' => '2021-12-13 06:07:53',
                    'updated_at' => '2022-12-06 08:03:15',
                    'category_data_center_id' => 9,
                    'order' => 86,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 80,
                    'name' => 'Buku Pencapaian Pelaksanaan TPB/SDGs Provinsi Kalimantan Timur 2019',
                    'file' => 'Buku Pencapaian Pelaksanaan TPB.SDGs Kalimantan Timur OK 2_compressed.pdf',
                    'created_at' => '2021-12-17 12:21:55',
                    'updated_at' => '2023-02-06 12:49:41',
                    'category_data_center_id' => 21,
                    'order' => 1,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 81,
                    'name' => 'LAPORAN SKM SEMESTER II TAHUN 2021',
                    'file' => 'LAPORAN SKM SEMESTER II TAHUN 2021_compressed.pdf',
                    'created_at' => '2022-01-06 02:57:18',
                    'updated_at' => '2022-01-06 02:57:18',
                    'category_data_center_id' => 15,
                    'order' => 3,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 82,
                    'name' => 'UU Nomor 3 Tahun 2022 Tentang Ibu Kota Negara',
                    'file' => 'UU Nomor 3 Tahun 2022_compressed.pdf',
                    'created_at' => '2022-02-20 15:35:31',
                    'updated_at' => '2022-02-20 15:35:31',
                    'category_data_center_id' => 9,
                    'order' => 101,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 83,
                    'name' => 'Laporan Resume Pengadaan Barang Jasa Tahun 2020',
                    'file' => '2020.rar',
                    'created_at' => '2022-03-17 04:55:28',
                    'updated_at' => '2022-03-17 04:55:28',
                    'category_data_center_id' => 23,
                    'order' => 1,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 84,
                    'name' => 'Laporan Resume Pengadaan Barang Jasa Tahun 2021',
                    'file' => '2021.rar',
                    'created_at' => '2022-03-17 04:55:49',
                    'updated_at' => '2022-03-17 04:55:49',
                    'category_data_center_id' => 23,
                    'order' => 2,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 85,
                    'name' => 'Standar Pelayanan BAPPEDA Tahun 2021',
                    'file' => 'STANDAR PELAYANAN BAPPEDA 2021_OK.pdf',
                    'created_at' => '2022-03-27 10:43:54',
                    'updated_at' => '2022-03-27 10:43:54',
                    'category_data_center_id' => 24,
                    'order' => 1,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 86,
                    'name' => 'Panduan Perangkat Daerah',
                    'file' => 'PANDUAN OPD_compressed.pdf',
                    'created_at' => '2022-12-02 04:19:25',
                    'updated_at' => '2022-12-06 06:50:43',
                    'category_data_center_id' => 25,
                    'order' => 3,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 87,
                    'name' => 'Panduan Perusahaan CSR',
                    'file' => 'PANDUAN PERUSAHAAN.pdf',
                    'created_at' => '2022-12-02 04:19:46',
                    'updated_at' => '2022-12-06 06:50:39',
                    'category_data_center_id' => 25,
                    'order' => 2,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 88,
                    'name' => 'Panduan Mitra Pembangunan',
                    'file' => 'PANDUAN MITRA PEMBANGUNAN.pdf',
                    'created_at' => '2022-12-02 04:20:18',
                    'updated_at' => '2022-12-06 06:50:34',
                    'category_data_center_id' => 25,
                    'order' => 1,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 89,
                    'name' => 'Sekretariat Tahun 2022',
                    'file' => 'SEKRETARIAT.zip',
                    'created_at' => '2022-12-06 07:22:30',
                    'updated_at' => '2022-12-06 07:44:47',
                    'category_data_center_id' => 26,
                    'order' => 7,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 90,
                    'name' => 'Evaluasi Jabatan Tahun 2022',
                    'file' => 'EVALUASI JABATAN.pdf',
                    'created_at' => '2022-12-06 07:23:11',
                    'updated_at' => '2022-12-06 07:44:53',
                    'category_data_center_id' => 26,
                    'order' => 2,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 91,
                    'name' => 'Peta Jabatan Penyetaraan',
                    'file' => 'PETA JABATAN PENYETARAAN 2022.pdf',
                    'created_at' => '2022-12-06 07:23:30',
                    'updated_at' => '2022-12-06 07:45:00',
                    'category_data_center_id' => 26,
                    'order' => 1,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 92,
                    'name' => 'Bidang P2EPD Tahun 2022',
                    'file' => '1. P2EPD.zip',
                    'created_at' => '2022-12-06 07:25:23',
                    'updated_at' => '2022-12-06 07:45:09',
                    'category_data_center_id' => 26,
                    'order' => 6,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 93,
                    'name' => 'Bidang PPM Tahun 2022',
                    'file' => '2. PPM.zip',
                    'created_at' => '2022-12-06 07:26:41',
                    'updated_at' => '2022-12-06 07:45:04',
                    'category_data_center_id' => 26,
                    'order' => 5,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 94,
                    'name' => 'Bidang Ekonomi Tahun 2022',
                    'file' => '3. PEREKONOMIAN DAN SDA.zip',
                    'created_at' => '2022-12-06 07:28:05',
                    'updated_at' => '2022-12-06 07:45:19',
                    'category_data_center_id' => 26,
                    'order' => 4,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 95,
                    'name' => 'Bidang Infraswil Tahun 2022',
                    'file' => '4. INFRASWIL.zip',
                    'created_at' => '2022-12-06 07:28:38',
                    'updated_at' => '2022-12-06 07:45:14',
                    'category_data_center_id' => 26,
                    'order' => 3,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 96,
                    'name' => 'Pergub No 11 Tahun 2020 Tentang SOTK Bappeda Prov Kaltim',
                    'file' => 'Pergub No 11 Tahun 2020 tentang SOTK Bappeda Prov. Kaltim_compressed.pdf',
                    'created_at' => '2022-12-06 08:01:30',
                    'updated_at' => '2022-12-06 08:04:02',
                    'category_data_center_id' => 9,
                    'order' => 93,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 97,
                    'name' => 'LAPORAN SKM SEMESTER II TAHUN 2022',
                    'file' => 'Laporan Hasil Pelaksanaan SKM Bappeda Prov. Kaltim Tahun 2022.pdf',
                    'created_at' => '2022-12-06 08:17:50',
                    'updated_at' => '2022-12-06 08:18:01',
                    'category_data_center_id' => 15,
                    'order' => 4,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 98,
                    'name' => 'Laporan Perekonomian Provinsi Kaltim Triwulan I Tahun 2020',
                    'file' => 'Buku Laporan Perekonomian Triwulan 1 Tahun 2022_compressed.pdf',
                    'created_at' => '2023-01-10 08:41:04',
                    'updated_at' => '2023-01-10 08:41:04',
                    'category_data_center_id' => 20,
                    'order' => 12,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 99,
                    'name' => 'Laporan Perekonomian Provinsi Kaltim Triwulan I Tahun 2021',
                    'file' => 'Buku Laporan Perekonomian Triwulan 1 Tahun 2021_compressed.pdf',
                    'created_at' => '2023-01-10 08:44:56',
                    'updated_at' => '2023-01-10 08:44:56',
                    'category_data_center_id' => 20,
                    'order' => 13,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 100,
                    'name' => 'Laporan Perekonomian Provinsi Kaltim Triwulan III Tahun 2021',
                    'file' => 'Buku Laporan Perekonomian Triwulan III-2021 OK_compressed.pdf',
                    'created_at' => '2023-01-10 08:51:26',
                    'updated_at' => '2023-01-10 08:51:26',
                    'category_data_center_id' => 20,
                    'order' => 14,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 101,
                    'name' => 'Laporan Perekonomian Provinsi Kaltim Triwulan I Tahun 2022',
                    'file' => 'Buku Laporan Perekonomian Triwulan 1 Tahun 2022_compressed.pdf',
                    'created_at' => '2023-01-10 08:53:23',
                    'updated_at' => '2023-01-10 08:53:23',
                    'category_data_center_id' => 20,
                    'order' => 15,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 102,
                    'name' => 'Laporan Analisis Ketimpangan Wilayah Tahun 2021',
                    'file' => 'Buku Analisis Ketimpangan Wilayah Tahun 2021_compressed.pdf',
                    'created_at' => '2023-01-10 08:57:48',
                    'updated_at' => '2023-01-10 08:57:48',
                    'category_data_center_id' => 27,
                    'order' => 1,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 103,
                    'name' => 'Laporan Analisis Ketimpangan Wilayah Tahun 2022',
                    'file' => 'Buku Analisis Ketimpangan Wilayah Provinsi Kalimantan Timur Tahun 2022_compressed.pdf',
                    'created_at' => '2023-01-10 08:58:05',
                    'updated_at' => '2023-01-10 08:58:05',
                    'category_data_center_id' => 27,
                    'order' => 2,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 104,
                    'name' => 'Laporan Perekonomian Provinsi Kaltim Triwulan II Tahun 2022',
                    'file' => 'Buku Laporan Perekonomian Triwulan II Tahun 2022 OK_compressed.pdf',
                    'created_at' => '2023-01-16 06:49:05',
                    'updated_at' => '2023-01-16 06:49:05',
                    'category_data_center_id' => 20,
                    'order' => 16,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 105,
                    'name' => 'Laporan Perekonomian Provinsi Kaltim Triwulan III Tahun 2022',
                    'file' => 'Buku Laporan Perekonomian Triwulan III Tahun 2022_compressed.pdf',
                    'created_at' => '2023-01-16 06:49:55',
                    'updated_at' => '2023-01-16 06:49:55',
                    'category_data_center_id' => 20,
                    'order' => 17,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 106,
                    'name' => 'Laporan Pelayanan Informasi Publik 2022',
                    'file' => 'Laporan Pelayanan Informasi Publik 2022.pdf',
                    'created_at' => '2023-02-01 02:53:41',
                    'updated_at' => '2023-02-01 04:44:42',
                    'category_data_center_id' => 13,
                    'order' => 7,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 107,
                    'name' => 'Laporan Pelayanan Informasi Publik 2021',
                    'file' => 'Laporan Pelayanan Informasi Publik 2021.pdf',
                    'created_at' => '2023-02-01 04:44:18',
                    'updated_at' => '2023-02-01 04:44:39',
                    'category_data_center_id' => 13,
                    'order' => 8,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 108,
                    'name' => 'Buku Pemantauan dan Evaluasi Capaian Pelaksanaan TPB/SDGs Provinsi Kalimantan Timur Tahun 2022',
                    'file' => 'Buku Pemantauan dan Evaluasi Capaian Pelaksanaan TPBSDGs Provinsi Kalimantan Timur Tahun 2022_compressed.pdf',
                    'created_at' => '2023-02-06 12:48:43',
                    'updated_at' => '2023-02-06 12:49:23',
                    'category_data_center_id' => 21,
                    'order' => 2,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 109,
                    'name' => 'Buku Rencana Aksi Daerah TPB/SDGs Provinsi Kalimantan Timur Tahun 2019-2023',
                    'file' => 'Buku RAD SDGs Tahun 2019 - 2023_compressed.pdf',
                    'created_at' => '2023-02-07 02:47:29',
                    'updated_at' => '2023-02-07 02:49:27',
                    'category_data_center_id' => 21,
                    'order' => 3,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 110,
                    'name' => 'Laporan Pelayanan Informasi Publik 2021',
                    'file' => 'Laporan Pelayanan Informasi Publik 2021.pdf',
                    'created_at' => '2023-02-24 08:16:12',
                    'updated_at' => '2023-02-24 08:17:42',
                    'category_data_center_id' => 16,
                    'order' => 5,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 111,
                    'name' => 'Laporan Tahunan Pengelolaan Informasi Publik PPID Tahun 2022',
                    'file' => 'Laporan Tahunan Pengelolaan Informasi Publik PPID Tahun 2022.pdf',
                    'created_at' => '2023-02-24 08:16:31',
                    'updated_at' => '2023-02-27 03:15:19',
                    'category_data_center_id' => 16,
                    'order' => 6,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 112,
                    'name' => 'Laporan Akses Informasi Publik 2021',
                    'file' => 'Laporan Akses Informasi Publik 2021.pdf',
                    'created_at' => '2023-02-24 08:18:04',
                    'updated_at' => '2023-02-24 08:18:04',
                    'category_data_center_id' => 16,
                    'order' => 4,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 113,
                    'name' => 'Formulir Keberatan Informasi',
                    'file' => 'Formulir Keberatan Informasi.docx',
                    'created_at' => '2023-02-27 01:48:54',
                    'updated_at' => '2023-02-27 01:48:54',
                    'category_data_center_id' => 17,
                    'order' => 2,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 114,
                    'name' => 'Lembar Informasi Dikecualikan Bappeda Kaltim 2022',
                    'file' => 'Lembar Informasi Dikecualikan Bappeda Kaltim 2022.pdf',
                    'created_at' => '2023-02-27 02:03:15',
                    'updated_at' => '2023-02-27 02:03:15',
                    'category_data_center_id' => 18,
                    'order' => 2,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 115,
                    'name' => 'SK PPID Bappeda Tahun 2022',
                    'file' => 'SK_Pengelola_Informasi_dan_Dokumentasi_Bappeda_Provinsi_Kaltim_Tahun.pdf',
                    'created_at' => '2023-09-07 01:54:46',
                    'updated_at' => '2023-09-07 01:54:46',
                    'category_data_center_id' => 16,
                    'order' => 3,
                    'slug' => Str::random(10),
                ],
                [
                    'id' => 116,
                    'name' => 'SK PPID Bappeda Tahun 2023',
                    'file' => 'Surat09072023094742.pdf',
                    'created_at' => '2023-09-07 01:58:46',
                    'updated_at' => '2023-09-07 01:58:46',
                    'category_data_center_id' => 16,
                    'order' => 4,
                    'slug' => Str::random(10),
                ],



            ]);


    }
}
