<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PejabatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('pejabats')->insert([
            [
                'id' => 1,
                'name' => 'Yusliando, ST',
                'jabatan' => 'KEPALA BADAN PERENCANAAN PEMBANGUNAN DAERAH',
                'status_aktif' => 1,
                'created_at' => '2020-11-10 06:37:48',
                'updated_at' => '2024-06-20 04:54:16',
                'foto' => 'YTKAg58kx91PtW1lmiIG.png',
                'bidang_id' => 6,
                'nip' => '196710051998031009',
                'golongan' => 'IV/c',
                'kelas_jabatan' => '15.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Cuti',
                'urutan_jabatan' => 1,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 2,
                'name' => 'Saur Parsaoran T, S.Pi, MEMD',
                'jabatan' => 'SEKRETARIS/PLT KABID INFRASTRUKTUR DAN KEWILAYAHAN',
                'status_aktif' => 1,
                'created_at' => '2020-11-10 06:39:34',
                'updated_at' => '2024-09-05 23:36:26',
                'foto' => 'K3G7VzY1VkRLhDq5QU9k.png',
                'bidang_id' => 1,
                'nip' => '197305071998031007',
                'golongan' => 'IV/b',
                'kelas_jabatan' => '11.A',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 2,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 3,
                'name' => 'Achmad Risa, S.E, M.M',
                'jabatan' => 'KEPALA SUB BAGIAN UMUM',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:47:50',
                'updated_at' => '2024-08-22 23:43:24',
                'foto' => 's8NwkTeZ17sy7icNSZox.png',
                'bidang_id' => 1,
                'nip' => '19770429200031003',
                'golongan' => 'IV/a',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 4,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 5,
                'name' => 'Duma Mangalie, S.E.',
                'jabatan' => 'PERENCANA AHLI MUDA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:50:26',
                'updated_at' => '2024-09-30 02:38:00',
                'foto' => 'F8X7uNM15013obEkR5ij.png',
                'bidang_id' => 2,
                'nip' => '197007071992031011',
                'golongan' => 'III/d',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 9,
                'ketua_tim' => 'ANALISIS DATA DAN INFORMASI',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 6,
                'name' => 'Alfino Rinaldi Arief, ST, M.E',
                'jabatan' => 'KABID PERENCANAAN PENGENDALIAN DAN EVALUASI PEMBANGUNAN DAERAH',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:51:07',
                'updated_at' => '2024-09-16 23:56:48',
                'foto' => '3dpUw3tZIDUQwZHYlIrt.png',
                'bidang_id' => 2,
                'nip' => '198705112010011007',
                'golongan' => 'III/d',
                'kelas_jabatan' => '11.A',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Dinas Luar',
                'urutan_jabatan' => 5,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 8,
                'name' => 'Muhammad Hamsani, ST, M.Si',
                'jabatan' => 'PERENCANA AHLI MUDA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:53:26',
                'updated_at' => '2024-09-30 02:38:30',
                'foto' => 'SJCKIsASlOWEGm8Dl39o.jpg',
                'bidang_id' => 3,
                'nip' => '198304242001121002',
                'golongan' => 'III/d',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 14,
                'ketua_tim' => 'DINAS PEMUDA DAN OLAH RAGA, BADAN PENELITIAN DAN PENGEMBANGAN DAERAH, DAN DINAS TENAGA KERJA DAN TRANSMIGRASI',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 10,
                'name' => 'Mispoyo, S.Pd., M.Pd',
                'jabatan' => 'KABID PEMERINTAH DAN PEMBANGUNAN MANUSIA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:54:34',
                'updated_at' => '2024-09-16 23:56:33',
                'foto' => 'kp0FywG7VGl6ifr2oVF6.png',
                'bidang_id' => 3,
                'nip' => '197603052002121007',
                'golongan' => 'IV/b',
                'kelas_jabatan' => '11.A',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Dinas Luar',
                'urutan_jabatan' => 6,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 11,
                'name' => 'Said Aboe Hanifah S.Sos.',
                'jabatan' => 'PERENCANA AHLI MUDA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:55:09',
                'updated_at' => '2024-09-30 02:34:00',
                'foto' => '2AfqT1gAX6P8VZ4F6MuY.png',
                'bidang_id' => 3,
                'nip' => '197407232009011002',
                'golongan' => 'III/d',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 11,
                'ketua_tim' => 'BADAN KEPEGAWAIAN DAERAH, DAN DINAS PERPUSTAKAAN DAN KEARSIPAN DAERAH',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 12,
                'name' => 'Asfiandi Zulfiar, S.T., M.URP.',
                'jabatan' => 'PERENCANA AHLI MUDA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:55:35',
                'updated_at' => '2024-09-30 02:34:18',
                'foto' => 'wA1bZ0zHkNzDmfKMevHD.png',
                'bidang_id' => 3,
                'nip' => '199001022010011001',
                'golongan' => 'III/d',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 13,
                'ketua_tim' => 'DINAS PENDIDIKAN DAN KEBUDAYAAN, DAN DINAS PEMBERDAYAAN MASYARAKAT DAN DESA',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 13,
                'name' => 'Perdana Jati Leksono, ST,M.Eng',
                'jabatan' => 'PERENCANA AHLI MUDA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:56:03',
                'updated_at' => '2024-09-30 02:37:34',
                'foto' => '3mXK4jYx6addBlKoCGpN.png',
                'bidang_id' => 3,
                'nip' => '198809192011011001',
                'golongan' => 'III/d',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Cuti',
                'urutan_jabatan' => 13,
                'ketua_tim' => 'BADAN PENGHUBUNG JAKARTA, SEKRETARIAT DPRD, DAN SATUAN POLISI PAMONG PRAJA',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 14,
                'name' => 'Wahyu Gatut Purboyo, S.Pi., M.Si',
                'jabatan' => 'KABID PEREKONOMIAN DAN SUMBER DAYA ALAM',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:56:33',
                'updated_at' => '2024-09-05 23:37:01',
                'foto' => 'bOKeXu7p0OotvJ9piPLD.png',
                'bidang_id' => 4,
                'nip' => '197104142002121005',
                'golongan' => 'IV/b',
                'kelas_jabatan' => '11.A',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 7,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 15,
                'name' => 'Agustina Rahmawati, S.Pi',
                'jabatan' => 'PERENCANA AHLI MUDA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:57:12',
                'updated_at' => '2024-09-30 02:45:36',
                'foto' => 'feMVsoMJxGWR2hFDHlhp.jpg',
                'bidang_id' => 4,
                'nip' => '199708072008012020',
                'golongan' => 'III/d',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 15,
                'ketua_tim' => 'DINAS PETERNAKAN DAN KESEHATAN HEWAN, DINAS KELAUTAN DAN PERIKANAN, DINAS PERKEBUNAN, DAN DINAS PANGAN TANAMAN PANGAN DAN HOLTIKULTURA',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 16,
                'name' => 'Dany Fachriza, S.T.',
                'jabatan' => 'PERENCANA AHLI MUDA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:57:49',
                'updated_at' => '2024-09-30 02:46:22',
                'foto' => '9Y0SIc2AqS6qZTaSGEsT.jpg',
                'bidang_id' => 4,
                'nip' => '197511152008011016',
                'golongan' => 'III/d',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 18,
                'ketua_tim' => 'DINAS PERINDUSTRIAN, PERDAGANGAN, KOPERASI, USAHA KECIL DAN MENENGAH, DAN DINAS PARIWISATA',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 17,
                'name' => 'Agus Taswanto, S.T., M.Ling.',
                'jabatan' => 'PERENCANA AHLI MUDA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:58:26',
                'updated_at' => '2024-09-30 02:46:02',
                'foto' => 'KkfKsqks144VhCXzBbZg.jpg',
                'bidang_id' => 4,
                'nip' => '199705242006041006',
                'golongan' => 'IV/a',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 17,
                'ketua_tim' => 'DINAS KEHUTANAN, DINAS ENERGI DAN SUMBER DAYA MINERAL, DAN DINAS LINGKUNGAN HIDUP',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 19,
                'name' => 'Dedy Pudja Wardana, S.T., M.Si.',
                'jabatan' => 'PERENCANA AHLI MUDA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:59:46',
                'updated_at' => '2024-12-10 01:58:20',
                'foto' => 'A44sKT0ribTGL4qsFSca.jpg',
                'bidang_id' => 5,
                'nip' => '197202152007011043',
                'golongan' => 'III/d',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 20,
                'ketua_tim' => 'DINAS PERHUBUNGAN, BIDANG BINA MARGA (PU), DAN UPTD 1, 2, DAN 3 (PU)',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 20,
                'name' => 'Ibnu Abbas, S.Sos, M.Si.',
                'jabatan' => 'PERENCANA AHLI MUDA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 19:00:28',
                'updated_at' => '2024-12-10 01:58:27',
                'foto' => 'Q8yk3O1zNwGf9gIh8NsR.jpg',
                'bidang_id' => 5,
                'nip' => '197510241998031006',
                'golongan' => 'IV/a',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 21,
                'ketua_tim' => 'BIDANG SUMBER DAYA AIR (PU), DAN BIDANG PENATAAN RUANG (PU)',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 21,
                'name' => 'Siti Rachmah Wulandari, S..T.',
                'jabatan' => 'PERENCANA AHLI MUDA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 19:01:03',
                'updated_at' => '2024-09-30 02:48:00',
                'foto' => 'ZZJ2mIUQTOTbOAt73mWG.jpg',
                'bidang_id' => 5,
                'nip' => '198506102009032007',
                'golongan' => 'III/d',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Cuti',
                'urutan_jabatan' => 22,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 24,
                'name' => 'Ahmad Hafizuddin, S.Hut',
                'jabatan' => 'PENGADMINISTRASI UMUM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:16:17',
                'updated_at' => '2024-03-28 01:38:37',
                'foto' => 'AoYxrfTE2F0dWAVnVyNl.jpg',
                'bidang_id' => 3,
                'nip' => '197201272007011015',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => 'BADAN PENGEMBANGAN SUMBER DAYA MANUSIA',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 25,
                'name' => 'Hj. Masriah S.E.',
                'jabatan' => 'ANALIS PERENCANAAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:16:19',
                'updated_at' => '2023-10-16 06:44:26',
                'foto' => 'QHvNslre4f1Mnso53ih3.jpg',
                'bidang_id' => null,
                'nip' => '197307261993032007',
                'golongan' => 'III/d',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 27,
                'name' => 'Rieka Indah Budiana, S.Sos., M.Si',
                'jabatan' => 'PENYUSUN RENCANA KEHUMASAN DAN PERPUSTAKAAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:19:25',
                'updated_at' => '2024-04-04 00:34:46',
                'foto' => 'xjbYNtUZV7DcFkQXHfOM.jpg',
                'bidang_id' => null,
                'nip' => '197808122008012027',
                'golongan' => 'IV/a',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 30,
                'name' => 'Zainul Husin S.Ap.',
                'jabatan' => 'PENGELOLA BAHAN PERENCANAAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:22:19',
                'updated_at' => '2024-04-04 00:38:54',
                'foto' => 'IBSgCRMybE0sqGRPO752.jpeg',
                'bidang_id' => null,
                'nip' => '197001041998031007',
                'golongan' => 'III/c',
                'kelas_jabatan' => '6.C',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 31,
                'name' => 'Syahruni HA',
                'jabatan' => 'PENGADMINISTRASI PERENCANAAN DAN PROGRAM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:22:38',
                'updated_at' => '2024-04-04 00:27:59',
                'foto' => 'jpWBMuGdcyV2cAYrGOfV.jpg',
                'bidang_id' => null,
                'nip' => '197009052007011026',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 33,
                'name' => 'Halimatussadiyah',
                'jabatan' => 'PRANATA TEKNOLOGI INFORMASI KOMPUTER',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:23:50',
                'updated_at' => '2024-04-04 00:27:30',
                'foto' => 'No1YOW1zps3aYOw9K7L0.jpg',
                'bidang_id' => null,
                'nip' => '197009142007012016',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 37,
                'name' => 'Heny Wati',
                'jabatan' => 'PENGADMINISTRASI UMUM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:25:23',
                'updated_at' => '2024-04-04 00:26:51',
                'foto' => 'tZiBNdvmkihad2LbHdo6.JPG',
                'bidang_id' => null,
                'nip' => '197912242007012007',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 38,
                'name' => 'Kartinem',
                'jabatan' => 'PRANATA TEKNOLOGI INFORMASI KOMPUTER',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:25:59',
                'updated_at' => '2024-04-04 00:26:38',
                'foto' => 'xClj1E0FmgpomTNLrYnU.jpg',
                'bidang_id' => null,
                'nip' => '197203212007012010',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 39,
                'name' => 'Nurmiana Afriany S.T., M.Sc.',
                'jabatan' => 'ANALIS PERENCANAAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:26:25',
                'updated_at' => '2024-04-04 00:28:19',
                'foto' => 'oMZZcDeyM8tGeocllkfg.jpg',
                'bidang_id' => null,
                'nip' => '198304162012122002',
                'golongan' => 'III/c',
                'kelas_jabatan' => '6.C',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 40,
                'name' => 'Sri Hartati, S.Sos',
                'jabatan' => 'PENGADMINISTRASI KEUANGAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:26:47',
                'updated_at' => '2024-04-04 00:25:38',
                'foto' => '2qhy4MApaZS0zd9G3eII.jpg',
                'bidang_id' => null,
                'nip' => '197509132007012006',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 41,
                'name' => 'Stella Felicia Sinaga, S.Si., M.UrbanPlanDes.',
                'jabatan' => 'KEPALA SUB BAGIAN PERENCANAAN PROGRAM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:26:55',
                'updated_at' => '2024-09-01 23:33:40',
                'foto' => 'iSEy5OMEBWi3Ol4MUaoN.png',
                'bidang_id' => 1,
                'nip' => '199002262011012001',
                'golongan' => 'III/d',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 3,
                'ketua_tim' => 'BIDANG CIPTA KARYA (PU), BIDANG JASA KONSTRUKSI (PU), SEKRETARIAT PU, DAN UPTD LABOLATORIUM (PU)',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 42,
                'name' => 'Ahmad Riyadi, S.Sos',
                'jabatan' => 'PENGADMINISTRASI SARANA DAN PRASARANA',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:27:33',
                'updated_at' => '2024-04-04 00:23:36',
                'foto' => 'okFFNsjgHFYuVzXo7Nv3.jpg',
                'bidang_id' => null,
                'nip' => '197806042007011009',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 44,
                'name' => 'Haris Amatiri',
                'jabatan' => 'PENGADMINISTRASI KEUANGAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:28:36',
                'updated_at' => '2024-04-04 00:25:18',
                'foto' => 'JXsih49FnsvPPbXgnbnP.jpg',
                'bidang_id' => null,
                'nip' => '197205242007011016',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 45,
                'name' => 'Kustaniah',
                'jabatan' => 'PENGADMINISTRASI KEUANGAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:29:31',
                'updated_at' => '2024-04-04 00:24:07',
                'foto' => 'UlKD2flCQne8nGpuSEVd.jpg',
                'bidang_id' => null,
                'nip' => '197608172007012019',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 47,
                'name' => 'Suwondo',
                'jabatan' => 'PENGADMINISTRASI PERENCANAAN DAN PROGRAM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:30:33',
                'updated_at' => '2024-04-04 00:26:19',
                'foto' => 'wyaHAganMBlYunvRtrLF.jpg',
                'bidang_id' => null,
                'nip' => '197404242007011025',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 49,
                'name' => 'Misbahul Jannah, S.Sos.',
                'jabatan' => 'PENGADMINISTRASI KEPEGAWAIAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:32:31',
                'updated_at' => '2024-04-04 00:26:05',
                'foto' => 'lvCawDkG8tCROUHPrTr6.jpg',
                'bidang_id' => null,
                'nip' => '197409012007012009',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 51,
                'name' => 'Kasim',
                'jabatan' => 'PENGADMINISTRASI UMUM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:33:19',
                'updated_at' => '2024-04-04 00:25:01',
                'foto' => '7glZFz3r5SoVk67kmrhH.jpg',
                'bidang_id' => null,
                'nip' => '197207082007011018',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 53,
                'name' => 'Suri Handayani, S.Sos.',
                'jabatan' => 'PENGADMINISTRASI UMUM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:33:55',
                'updated_at' => '2024-04-04 00:25:54',
                'foto' => 'XVM2odTwZFsIEAmw07rt.jpg',
                'bidang_id' => null,
                'nip' => '197409062007012015',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 54,
                'name' => 'Erika Wahyu Sartika',
                'jabatan' => 'PENGADMINISTRASI PERENCANAAN DAN PROGRAM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:34:30',
                'updated_at' => '2024-04-04 00:23:54',
                'foto' => '1ccM5kJPUnHB0c6XrTo1.JPG',
                'bidang_id' => null,
                'nip' => '197410272007012008',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 55,
                'name' => 'Ramlie',
                'jabatan' => 'PENGADMINISTRASI RUMAH TANGGA PRODUKSI',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:34:31',
                'updated_at' => '2023-10-16 06:51:31',
                'foto' => 'idFSajZpjTeHunF9g0sC.jpg',
                'bidang_id' => null,
                'nip' => '196705241988031005',
                'golongan' => 'III/b',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 56,
                'name' => 'H. Mukti Ali',
                'jabatan' => 'PENGADMINISTRASI PENERIMAAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:35:18',
                'updated_at' => '2023-10-16 06:47:30',
                'foto' => 'xr3do4HJcLAGh6jmd9eD.jpg',
                'bidang_id' => null,
                'nip' => '196806131993011002',
                'golongan' => 'III/b',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 57,
                'name' => 'Retno Sulistiyo, S.Sos.',
                'jabatan' => 'PENGADMINISTRASI KEPEGAWAIAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:35:21',
                'updated_at' => '2024-04-04 00:24:41',
                'foto' => '6h8MXeZL8rRIscOqRuQS.jpg',
                'bidang_id' => null,
                'nip' => '197511282007012010',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 59,
                'name' => 'Doney',
                'jabatan' => 'PENGADMINISTRASI UMUM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:36:54',
                'updated_at' => '2023-10-16 06:51:14',
                'foto' => 'UDuE1QvP2PxlHRJ0ZNYb.jpg',
                'bidang_id' => null,
                'nip' => '196812261993031010',
                'golongan' => 'III/b',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 60,
                'name' => 'Rahmat Hidayat, S.Sos',
                'jabatan' => 'PENGADMINISTRASI PERENCANAAN DAN PROGRAM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:37:45',
                'updated_at' => '2024-04-04 00:36:32',
                'foto' => 'pvh6tSJUoa2clpRcO2z0.jpg',
                'bidang_id' => null,
                'nip' => '197204152007011031',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 62,
                'name' => 'M. Agus Hendra, S.Sos.',
                'jabatan' => 'PENGADMINISTRASI KEPEGAWAIAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:38:39',
                'updated_at' => '2024-04-04 00:23:06',
                'foto' => '5T9AABuP0pGq7TyWGvO8.JPG',
                'bidang_id' => null,
                'nip' => '197712152007011017',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 63,
                'name' => 'Dwi Ery Mujahiddin  S.Hut., M.P.',
                'jabatan' => 'ANALIS PERENCANAAN STRATEGIS',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:39:15',
                'updated_at' => '2024-04-04 00:38:25',
                'foto' => 'Zdkp7CJ2YRjqwMftmcqh.jpg',
                'bidang_id' => 2,
                'nip' => '197502052009011006',
                'golongan' => 'III/c',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => 'PENGENDALIAN, EVALUASI, DAN PELAPORAN',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 64,
                'name' => 'Nazly Nahdiar',
                'jabatan' => 'PENGADMINISTRASI PERENCANAAN DAN PROGRAM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:39:17',
                'updated_at' => '2024-04-04 00:22:51',
                'foto' => 'XD4oKctFwFWwPkV5NRVP.jpg',
                'bidang_id' => null,
                'nip' => '197904272008011016',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 65,
                'name' => 'Shinta Lakhsmi Sari',
                'jabatan' => 'PENGADMINISTRASI PERENCANAAN DAN PROGRAM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:40:11',
                'updated_at' => '2024-04-04 00:22:16',
                'foto' => 'Xf22luuFOD6YuYBCzhDF.jpg',
                'bidang_id' => null,
                'nip' => '197710252008012024',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 66,
                'name' => 'Fryma Putra Pratama S.T.',
                'jabatan' => 'PERENCANA AHLI PERTAMA',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:40:16',
                'updated_at' => '2024-09-30 02:48:14',
                'foto' => 'eraCjCIo5zrCOkIvkUgq.png',
                'bidang_id' => 5,
                'nip' => '198902162015031001',
                'golongan' => 'III/b',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 23,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 68,
                'name' => 'Senindiyanto',
                'jabatan' => 'PENGADMINISTRASI PERSURATAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:41:25',
                'updated_at' => '2024-04-04 00:22:32',
                'foto' => 'RX1pD9ZvFvuYzLM6JTat.jpg',
                'bidang_id' => null,
                'nip' => '197504062008011016',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 69,
                'name' => 'Basri Saryati S.E.',
                'jabatan' => 'PENGELOLA KEGIATAN DAN ANGGARAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:41:55',
                'updated_at' => '2024-04-04 00:32:08',
                'foto' => 'Z9AU94CXTYN4iOtnYXeh.jpg',
                'bidang_id' => null,
                'nip' => '197211172007012006',
                'golongan' => 'III/c',
                'kelas_jabatan' => '6.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 70,
                'name' => 'Suherman',
                'jabatan' => 'PENGADMINISTRASI PERENCANAAN DAN PROGRAM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:41:59',
                'updated_at' => '2023-10-16 06:36:37',
                'foto' => '8jZFJeHRH8xQftqQ2H0a.jpeg',
                'bidang_id' => null,
                'nip' => '197805052008011028',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 71,
                'name' => 'Maretawiah Har',
                'jabatan' => 'PENGADMINISTRASI UMUM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:42:39',
                'updated_at' => '2024-04-04 00:21:59',
                'foto' => 'QQFEWv7PE4DgZBu7ZIrb.jpg',
                'bidang_id' => null,
                'nip' => '198003112008012022',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 72,
                'name' => 'Rudi Hertamiaji S.Sos.',
                'jabatan' => 'PENGADMINISTRASI PERENCANAAN DAN PROGRAM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:42:47',
                'updated_at' => '2024-04-04 00:31:56',
                'foto' => '3tdr3TkLqYK7HlFwkLvr.jpg',
                'bidang_id' => null,
                'nip' => '196802162007011015',
                'golongan' => 'III/c',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 73,
                'name' => 'Noordiansyah S.E.',
                'jabatan' => 'PENYUSUN RENCANA KEBUTUHAN SARANA DAN PRASARANA',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:43:36',
                'updated_at' => '2024-04-04 00:31:44',
                'foto' => 'pyl92iPGD5xwX1OoOmPv.jpg',
                'bidang_id' => null,
                'nip' => '197610152007011014',
                'golongan' => 'III/c',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 74,
                'name' => 'Darham',
                'jabatan' => 'PENGADMINISTRASI PERSURATAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:43:48',
                'updated_at' => '2023-10-16 06:37:45',
                'foto' => 'YAzEJrFodRSREDR9ba5i.jpg',
                'bidang_id' => null,
                'nip' => '196808122009011001',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 75,
                'name' => 'Ardiansyah',
                'jabatan' => 'PRANATA TEKNOLOGI INFORMASI KOMPUTER',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:44:36',
                'updated_at' => '2023-10-16 06:36:13',
                'foto' => 'Q7BqR9sAYmoJJjFekIfb.jpg',
                'bidang_id' => null,
                'nip' => '197602212009011002',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 76,
                'name' => 'Astien Ariyani  S.E.',
                'jabatan' => 'ANALIS PERENCANAAN ANGGARAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:44:51',
                'updated_at' => '2024-04-04 00:31:29',
                'foto' => 'G3uBUPvejZlu9oM8Lz0J.JPG',
                'bidang_id' => 3,
                'nip' => '198111302009012002',
                'golongan' => 'III/c',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => 'DINAS PEMBERDAYAAN MASYARAKAT DAN PEMERINTAHAN DESA, DAN DINAS KEPENDUDUKAN PEMBERDAYAAN PEREMPUAN DAN PERLINDUNGAN ANAK',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 77,
                'name' => 'Tabrani A.',
                'jabatan' => 'PENGADMINISTRASI UMUM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:45:22',
                'updated_at' => '2024-04-04 00:20:53',
                'foto' => 'ephD06mO2g1CIdmmh5ae.jpg',
                'bidang_id' => null,
                'nip' => '197708132014061002',
                'golongan' => 'II/c',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 79,
                'name' => 'Rusman',
                'jabatan' => 'PENGADMINISTRASI UMUM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:46:02',
                'updated_at' => '2024-04-04 00:20:35',
                'foto' => 'w7hcPSnlW4HMwkG2ItVf.jpg',
                'bidang_id' => null,
                'nip' => '197908042014061001',
                'golongan' => 'II/c',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 80,
                'name' => 'Farisa S.E.',
                'jabatan' => 'PENATA LAPORAN KEUANGAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:46:40',
                'updated_at' => '2024-04-04 00:31:17',
                'foto' => 'cWE5o3gDcyGbvdmUPWvy.jpg',
                'bidang_id' => null,
                'nip' => '197112162002122005',
                'golongan' => 'III/c',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 82,
                'name' => 'Sukandar S.Sos.',
                'jabatan' => 'ANALIS PEMERINTAHAN UMUM DAN OTONOMI DAERAH',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:47:22',
                'updated_at' => '2024-03-05 06:04:20',
                'foto' => '9Mm7zkexJaaa4c3ESswO.jpg',
                'bidang_id' => 3,
                'nip' => '196903312007011013',
                'golongan' => 'III/b',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => 'BADAN PERENCANAAN PEMBANGUNAN DAERAH, DAN INSPEKTORAT WILAYAH',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 83,
                'name' => 'Slamet Hariyanto A.Md., S.Akun.',
                'jabatan' => 'PENGELOLA KEUANGAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:48:04',
                'updated_at' => '2024-04-04 00:37:43',
                'foto' => 'md9F8OqKCck77jHfEJsU.jpg',
                'bidang_id' => null,
                'nip' => '198306292009031003',
                'golongan' => 'III/b',
                'kelas_jabatan' => '6.C',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 85,
                'name' => 'Mico Iswawan',
                'jabatan' => 'PRANATA TEKNOLOGI INFORMASI KOMPUTER',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:48:51',
                'updated_at' => '2023-10-16 06:35:18',
                'foto' => '323hlctWQLE6wsJqgK1T.jpg',
                'bidang_id' => null,
                'nip' => '197110202009011001',
                'golongan' => 'II/b',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 86,
                'name' => 'Ali Mudzakkir Hamidi S.STP',
                'jabatan' => 'ANALIS PENGEMBANGAN WILAYAH',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:49:48',
                'updated_at' => '2024-03-27 02:50:40',
                'foto' => '01MPM1DKSYcqrOOeuMRo.png',
                'bidang_id' => 3,
                'nip' => '199509042017081001',
                'golongan' => 'III/b',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => 'SEKRETARIAT DAERAH, DAN BADAN KESATUAN BANGSA DAN POLITIK',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 87,
                'name' => 'Irwansyah',
                'jabatan' => 'PENGADMINISTRASI TEKNIS PEMERIKSAAN DAN PERAWATAN KENDARAAN BERMOTOR',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:50:20',
                'updated_at' => '2023-10-16 06:33:35',
                'foto' => 'wCYphVHcHPvJQsbn3BZ7.jpg',
                'bidang_id' => null,
                'nip' => '196703072007011020',
                'golongan' => 'II/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 88,
                'name' => 'Hastati Paturusi S.H.',
                'jabatan' => 'ARSIPARIS AHLI PERTAMA',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:50:48',
                'updated_at' => '2023-10-16 06:33:22',
                'foto' => 'dBZfg8O9WlQE4WC08dU5.jpg',
                'bidang_id' => null,
                'nip' => '197910222008012020',
                'golongan' => 'III/a',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 89,
                'name' => 'Yunan Junaidi',
                'jabatan' => 'PRAMU BAKTI',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:51:03',
                'updated_at' => '2024-04-04 00:19:47',
                'foto' => 'dWvc5u6z7IeWbtIkrjtE.jpg',
                'bidang_id' => null,
                'nip' => '197003152008011014',
                'golongan' => 'II/a',
                'kelas_jabatan' => '1.A',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 90,
                'name' => 'Yasin Purnomo',
                'jabatan' => 'PRAMU BAKTI',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:51:36',
                'updated_at' => '2024-04-04 00:19:28',
                'foto' => 'HEjW5uJ45t0Y4RpvH8KB.jpg',
                'bidang_id' => null,
                'nip' => '198503232010011002',
                'golongan' => 'I/d',
                'kelas_jabatan' => '1.A',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 91,
                'name' => 'Muhammad Hendra Wahyudi, S.Ap',
                'jabatan' => 'PENGADMINISTRASI SARANA DAN PRASARANA',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:52:12',
                'updated_at' => '2024-04-04 00:37:19',
                'foto' => 'TbX4hPxqXKIrAYPie5RE.jpg',
                'bidang_id' => null,
                'nip' => '197710312002121005',
                'golongan' => 'III/b',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 92,
                'name' => 'Aseri',
                'jabatan' => 'PENGADMINISTRASI PERSURATAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:53:16',
                'updated_at' => '2024-03-27 02:50:20',
                'foto' => 'SHFq2uhCqx4aCQVFkflT.png',
                'bidang_id' => null,
                'nip' => '196805142000121001',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 96,
                'name' => 'Angki Setyadarma, S.STP',
                'jabatan' => 'PENYUSUN RENCANA SARANA PENGEMBANGAN USAHA',
                'status_aktif' => 1,
                'created_at' => '2022-01-24 07:07:24',
                'updated_at' => '2024-04-16 01:00:56',
                'foto' => 'yeWwTglsonGgVJb4z5fC.png',
                'bidang_id' => 4,
                'nip' => '199508232017081002',
                'golongan' => 'III/b',
                'kelas_jabatan' => '-',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => 'BADAN PENGELOLAAN KEUANGAN DAN ASET DAERAH, DAN BADAN PENDAPATAN DAERAH',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 97,
                'name' => 'M. Isnainil Hude S.Si.',
                'jabatan' => 'PERENCANA AHLI PERTAMA',
                'status_aktif' => 1,
                'created_at' => '2023-01-16 00:49:03',
                'updated_at' => '2024-09-30 02:26:02',
                'foto' => 'lrxjeV90uDrVyp4Qoiod.png',
                'bidang_id' => 2,
                'nip' => '198411192014021001',
                'golongan' => 'III/b',
                'kelas_jabatan' => null,
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 10,
                'ketua_tim' => 'PERENCANAAN DAN PENDANAAN PEMBANGUNAN',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 98,
                'name' => 'Ardian Nur, S.STP.',
                'jabatan' => 'PENYUSUN PROGRAM ANGGARAN DAN PELAPORAN',
                'status_aktif' => 1,
                'created_at' => '2023-10-16 02:38:49',
                'updated_at' => '2024-04-29 04:07:38',
                'foto' => 'rl55l3qnskOsoh9y1o0L.png',
                'bidang_id' => 3,
                'nip' => '199606302018011001',
                'golongan' => 'III/b',
                'kelas_jabatan' => null,
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => 'DINAS KOMUNIKASI DAN INFORMATIKA, DAN BADAN PENANGGULANGAN BENCANA DAERAH',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 100,
                'name' => 'Siti Djulaeha Lawarakan, S.E.',
                'jabatan' => 'ANALIS PERENCANAAN',
                'status_aktif' => 1,
                'created_at' => '2023-10-16 02:41:39',
                'updated_at' => '2024-03-27 02:49:55',
                'foto' => 'pCxgvzZlqxUjWlc3CCHR.png',
                'bidang_id' => null,
                'nip' => '198002022000122002',
                'golongan' => 'III/d',
                'kelas_jabatan' => null,
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 101,
                'name' => 'Annisa Ghiffary Dwi Ningtyas, A.Md.Kb.N.',
                'jabatan' => 'PENGATUR KEUANGAN',
                'status_aktif' => 1,
                'created_at' => '2023-10-16 02:43:08',
                'updated_at' => '2024-03-27 00:09:33',
                'foto' => 'wPdgViWBiYxoK0erDDj7.png',
                'bidang_id' => null,
                'nip' => '200007282022012004',
                'golongan' => 'II/c',
                'kelas_jabatan' => null,
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 102,
                'name' => 'Rayhard Maulana Sahrullah, A.Md.Ak.',
                'jabatan' => 'VERIFIKATUR KEUANGAN',
                'status_aktif' => 1,
                'created_at' => '2023-10-16 02:44:26',
                'updated_at' => '2024-03-28 03:46:51',
                'foto' => 'tAlPK0Rg6YpxlLmeOsGp.png',
                'bidang_id' => null,
                'nip' => '200009222022011001',
                'golongan' => 'II/c',
                'kelas_jabatan' => null,
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 103,
                'name' => 'Sri Hastuti, S.T.',
                'jabatan' => 'ANALIS PERENCANAAN STRATEGIS',
                'status_aktif' => 1,
                'created_at' => '2024-03-25 00:06:55',
                'updated_at' => '2024-03-27 00:36:31',
                'foto' => 'BzUwpi2WFKp7RqbrZDSd.png',
                'bidang_id' => null,
                'nip' => '198212202015032000',
                'golongan' => 'III/c',
                'kelas_jabatan' => null,
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 104,
                'name' => 'Monika Uli Gultom, M.H.',
                'jabatan' => 'PENELAAH TEKNIS KEBIJAKAN',
                'status_aktif' => 1,
                'created_at' => '2024-09-30 02:51:24',
                'updated_at' => '2024-09-30 02:51:24',
                'foto' => 'BWe1CRiGOcJ2B8DhH0j4.png',
                'bidang_id' => null,
                'nip' => '198212082010012014',
                'golongan' => 'III/d',
                'kelas_jabatan' => null,
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 105,
                'name' => 'Nida Halimahtussa\'diyyah, S.Tr.IP.',
                'jabatan' => 'FASILITATOR PEMERINTAHAN',
                'status_aktif' => 1,
                'created_at' => '2024-09-30 07:36:39',
                'updated_at' => '2024-09-30 07:36:39',
                'foto' => 'Z7tf1Rxo9viMjQlHfqT8.png',
                'bidang_id' => 3,
                'nip' => '200206122024092001',
                'golongan' => 'III/a',
                'kelas_jabatan' => null,
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => null,
                'ketua_tim' => null,
                'slug' => Str::slug(Str::random(10)),
            ],
        ]);
    }
}
