<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PejabatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('pejabats')->insert(
            [
                'id' => 1,
                'name' => 'Yusliando, ST',
                'jabatan' => 'KEPALA BADAN PERENCANAAN PEMBANGUNAN DAERAH',
                'status_aktif' => 1,
                'created_at' => '2020-11-10 06:37:48',
                'updated_at' => '2024-06-20 04:54:16',
                'foto' => 'YTKAg58kx91PtW1lmiIG.png',
                'bidang_id' => 6,
                'nip' => '196710051998031009',
                'golongan' => 'IV/c',
                'kelas_jabatan' => '15.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Cuti',
                'urutan_jabatan' => 1,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 2,
                'name' => 'Saur Parsaoran T, S.Pi, MEMD',
                'jabatan' => 'SEKRETARIS',
                'status_aktif' => 1,
                'created_at' => '2020-11-10 06:39:34',
                'updated_at' => '2023-10-09 05:13:22',
                'foto' => 'kLcRW5nYAdBRQNgZVzBs.jpg',
                'bidang_id' => 1,
                'nip' => '197305071998031007',
                'golongan' => 'IV/b',
                'kelas_jabatan' => '11.A',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 2,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 3,
                'name' => 'Achmad Risa, S.E, M.M',
                'jabatan' => 'KEPALA SUB BAGIAN UMUM',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:47:50',
                'updated_at' => '2023-10-09 05:14:03',
                'foto' => 'jfldIA7XTvJ4hAIssaFI.png',
                'bidang_id' => 1,
                'nip' => '19770429200031003',
                'golongan' => 'IV/a',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 4,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 5,
                'name' => 'Duma Mangalie, S.E.',
                'jabatan' => 'PERENCANA AHLI MUDA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:50:26',
                'updated_at' => '2023-10-09 07:53:29',
                'foto' => 'cSayUeKkLKj9CWMfQUYi.jpg',
                'bidang_id' => 1,
                'nip' => '197007071992031011',
                'golongan' => 'III/d',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 9,
                'ketua_tim' => 'ANALISIS DATA DAN INFORMASI',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 6,
                'name' => 'Alfino Rinaldi Arief, ST, M.E',
                'jabatan' => 'KABID PERENCANAAN PENGENDALIAN DAN EVALUASI PEMBANGUNAN DAERAH',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:51:07',
                'updated_at' => '2024-06-20 05:21:55',
                'foto' => 'fQqOknTb3SEM5tvIf2zg.png',
                'bidang_id' => 2,
                'nip' => '198705112010011007',
                'golongan' => 'III/d',
                'kelas_jabatan' => '11.A',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Tugas Luar Kantor',
                'urutan_jabatan' => 5,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 8,
                'name' => 'Muhammad Hamsani, ST, M.Si',
                'jabatan' => 'PERENCANA AHLI MUDA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:53:26',
                'updated_at' => '2023-11-14 00:50:54',
                'foto' => 'svxHCcJXxjJvGyBYMTDm.jpg',
                'bidang_id' => 3,
                'nip' => '198304242001121002',
                'golongan' => 'III/d',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 13,
                'ketua_tim' => 'DINAS PEMUDA DAN OLAH RAGA, BADAN PENELITIAN DAN PENGEMBANGAN DAERAH, DAN DINAS TENAGA KERJA DAN TRANSMIGRASI',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 10,
                'name' => 'Mispoyo, S.Pd., M.Pd',
                'jabatan' => 'KABID PEMERINTAH DAN PEMBANGUNAN MANUSIA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:54:34',
                'updated_at' => '2023-10-09 05:14:31',
                'foto' => '3revgv9AeNLK9DTgY8fC.png',
                'bidang_id' => 3,
                'nip' => '197603052002121007',
                'golongan' => 'IV/b',
                'kelas_jabatan' => '11.A',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Tidak Ada Keterangan',
                'urutan_jabatan' => 6,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 11,
                'name' => 'Said Aboe Hanifah S.Sos.',
                'jabatan' => 'PERENCANA AHLI MUDA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:55:09',
                'updated_at' => '2023-10-09 07:05:03',
                'foto' => 'cZLxuwnIYVAljc9oOC8a.png',
                'bidang_id' => 3,
                'nip' => '197407232009011002',
                'golongan' => 'III/d',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Tidak Ada Keterangan',
                'urutan_jabatan' => 10,
                'ketua_tim' => 'BADAN KEPEGAWAIAN DAERAH, DAN DINAS PERPUSTAKAAN DAN KEARSIPAN DAERAH',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 12,
                'name' => 'Asfiandi Zulfiar, S.T., M.URP.',
                'jabatan' => 'PERENCANA AHLI MUDA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:55:35',
                'updated_at' => '2023-10-09 07:11:27',
                'foto' => '3KKAuqdZAvwbpjkQkHzM.jpeg',
                'bidang_id' => 3,
                'nip' => '198508292010011015',
                'golongan' => 'III/c',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Tidak Ada Keterangan',
                'urutan_jabatan' => 11,
                'ketua_tim' => 'DINAS KESEHATAN, RUMAH SAKIT AWS, RUMAH SAKIT ATMA HUSADA, DAN RUMAH SAKIT KANUJOSO',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 13,
                'name' => 'Perdana Jati Leksono, ST,M.Eng',
                'jabatan' => 'PERENCANA AHLI MUDA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:56:03',
                'updated_at' => '2023-10-09 07:48:17',
                'foto' => '6d7cmoKon2cUb6OTUnLN.png',
                'bidang_id' => 3,
                'nip' => '198809192011011001',
                'golongan' => 'III/c',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Tidak Ada Keterangan',
                'urutan_jabatan' => 12,
                'ketua_tim' => 'BADAN PENGHUBUNG JAKARTA, SEKRETARIAT DPRD, DAN SATUAN POLISI PAMONG PRAJA',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 14,
                'name' => 'Wahyu Gatut Purboyo, S.Pi., M.Si',
                'jabatan' => 'KABID PEREKONOMIAN DAN SUMBER DAYA ALAM',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:56:33',
                'updated_at' => '2023-10-12 00:23:11',
                'foto' => 'V4E8cDJqDA0xC7QvdvuR.png',
                'bidang_id' => 4,
                'nip' => '197104142002121005',
                'golongan' => 'IV/a',
                'kelas_jabatan' => '11.A',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 7,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 15,
                'name' => 'Agustina Rahmawati, S.Pi',
                'jabatan' => 'PERENCANA AHLI MUDA SEBAGAI KETUA TIM PERTANIAN DAN PERIKANAN',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:57:12',
                'updated_at' => '2023-10-12 00:23:03',
                'foto' => 'TS0K4542efzOkRLCuxUA.PNG',
                'bidang_id' => 4,
                'nip' => '199708072008012020',
                'golongan' => 'III/d',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Dinas Luar',
                'urutan_jabatan' => 14,
                'ketua_tim' => 'DINAS PETERNAKAN DAN KESEHATAN HEWAN, DINAS KELAUTAN DAN PERIKANAN, DINAS PERKEBUNAN, DAN DINAS PANGAN TAnameN PANGAN DAN HOLTIKULTURA',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 16,
                'name' => 'Dany Fachriza , S.T.',
                'jabatan' => 'PERENCANA AHLI MUDA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:57:49',
                'updated_at' => '2023-10-09 06:58:54',
                'foto' => 'SZs0FAPmUxEsfnGhOgez.PNG',
                'bidang_id' => 4,
                'nip' => '197511152008011016',
                'golongan' => 'III/d',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 17,
                'ketua_tim' => 'DINAS PERINDUSTRIAN, PERDAGANGAN, KOPERASI, USAHA KECIL DAN MENENGAH, DAN DINAS PARIWISATA',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 17,
                'name' => 'Agus Taswanto, S.T.',
                'jabatan' => 'PERENCANA AHLI MUDA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:58:26',
                'updated_at' => '2023-10-09 06:53:00',
                'foto' => 'qjolajiJZzevLzpEzmRA.jpg',
                'bidang_id' => 4,
                'nip' => '199705242006041006',
                'golongan' => 'IV/a',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 16,
                'ketua_tim' => 'DINAS KEHUTANAN, DINAS ENERGI DAN SUMBER DAYA MINERAL, DAN DINAS LINGKUNGAN HIDUP',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 18,
                'name' => 'Baihaqi Hazami, S.T., M.Si.',
                'jabatan' => 'KABID INFRASTRUKTUR DAN KEWILAYAHAN',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:58:59',
                'updated_at' => '2023-10-10 00:46:09',
                'foto' => NULL,
                'bidang_id' => 5,
                'nip' => '-',
                'golongan' => 'IV/b',
                'kelas_jabatan' => '11.A',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 8,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 19,
                'name' => 'Dedy Pudja Wardana, S.T.',
                'jabatan' => 'PERENCANA AHLI MUDA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 18:59:46',
                'updated_at' => '2023-10-10 00:45:40',
                'foto' => '3IsXhjju8Z8UxKfL5zaB.jpg',
                'bidang_id' => 5,
                'nip' => '197202152007011043',
                'golongan' => 'III/d',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 17,
                'ketua_tim' => 'DINAS PERHUBUNGAN, BIDANG BINA MARGA (PU), DAN UPTD 1, 2, DAN 3 (PU)',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 20,
                'name' => 'Ibnu Abbas, S.Sos, M.Si.',
                'jabatan' => 'PERENCANA AHLI MUDA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 19:00:28',
                'updated_at' => '2023-10-09 07:51:43',
                'foto' => '2oveiOpuDutT3Jrs45ok.jpg',
                'bidang_id' => 5,
                'nip' => '197510241998031006',
                'golongan' => 'IV/a',
                'kelas_jabatan' => '9.C',
                'status_pns' => 'Pejabat',
                'status_kehadiran' => 'Dinas Luar',
                'urutan_jabatan' => 18,
                'ketua_tim' => 'BIDANG SUMBER DAYA AIR (PU), DAN BIDANG PENATAAN RUANG (PU)',
                'slug' => Str::slug(Str::random(10)),
            ],

            [
                'id' => 21,
                'name' => 'Siti Rachmah Wulandari, ST',
                'jabatan' => 'PERENCANA AHLI MUDA',
                'status_aktif' => 1,
                'created_at' => '2021-01-25 19:01:03',
                'updated_at' => '2023-10-09 05:30:56',
                'foto' => 'N2tlfVonu1HKgYSTjB8X.PNG',
                'bidang_id' => 5,
                'nip' => '198506102009032007',
                'golongan' => 'III/c',
                'kelas_jabatan' => '9.C',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Cuti',
                'urutan_jabatan' => 19,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 24,
                'name' => 'Ahmad Hafizuddin, S.Hut',
                'jabatan' => 'PENGADMINISTRASI UMUM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:16:17',
                'updated_at' => '2023-10-09 07:08:04',
                'foto' => 'AoYxrfTE2F0dWAVnVyNl.jpg',
                'bidang_id' => NULL,
                'nip' => '197201272007011015',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => 'BADAN PENGEMBANGAN SUMBER DAYA MANUSIA',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 25,
                'name' => 'Hj. Masriah S.E.',
                'jabatan' => 'ANALIS PERENCANAAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:16:19',
                'updated_at' => '2023-10-09 05:39:36',
                'foto' => 'QHvNslre4f1Mnso53ih3.jpg',
                'bidang_id' => NULL,
                'nip' => '197307261993032007',
                'golongan' => 'III/d',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 27,
                'name' => 'Rieka Indah Budiana, S.Sos., M.Si',
                'jabatan' => 'PENYUSUN RENCANA KEHUMASAN DAN PERPUSTAKAAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:19:25',
                'updated_at' => '2023-10-09 05:46:19',
                'foto' => 'xjbYNtUZV7DcFkQXHfOM.jpg',
                'bidang_id' => NULL,
                'nip' => '197808122008012027',
                'golongan' => 'III/d',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 28,
                'name' => 'Halabi Zada Fitriana A.Md.',
                'jabatan' => 'PENGELOLA SISTEM INFORMASI GEOGRAFIS',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:19:49',
                'updated_at' => '2023-10-09 05:55:03',
                'foto' => 'm2BaJnw9cD9phInj2hIZ.JPG',
                'bidang_id' => NULL,
                'nip' => '199104162015032002',
                'golongan' => 'II/d',
                'kelas_jabatan' => '6.D',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 30,
                'name' => 'Zainul Husin A.Md.',
                'jabatan' => 'PENGELOLA BAHAN PERENCANAAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:22:19',
                'updated_at' => '2023-10-09 05:46:33',
                'foto' => 'IBSgCRMybE0sqGRPO752.jpeg',
                'bidang_id' => NULL,
                'nip' => '197001041998031007',
                'golongan' => 'III/c',
                'kelas_jabatan' => '6.C',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 31,
                'name' => 'Syahruni HA',
                'jabatan' => 'PENGADMINISTRASI PERENCANAAN DAN PROGRAM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:22:38',
                'updated_at' => '2023-10-09 05:47:56',
                'foto' => 'jpWBMuGdcyV2cAYrGOfV.jpg',
                'bidang_id' => NULL,
                'nip' => '197009052007011026',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 33,
                'name' => 'Halimatussadiyah',
                'jabatan' => 'PRANATA TEKNOLOGI INFORMASI KOMPUTER',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:23:50',
                'updated_at' => '2023-10-09 05:53:23',
                'foto' => 'No1YOW1zps3aYOw9K7L0.jpg',
                'bidang_id' => NULL,
                'nip' => '197009142007012016',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 35,
                'name' => 'Endang Rusdianto',
                'jabatan' => 'PENGADMINISTRASI PERENCANAAN DAN PROGRAM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:24:38',
                'updated_at' => '2023-10-09 05:49:49',
                'foto' => 'cHaVnSIdWvAOc1JXemQU.jpg',
                'bidang_id' => NULL,
                'nip' => '196605092007011017',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 37,
                'name' => 'Heny Wati',
                'jabatan' => 'PENGADMINISTRASI UMUM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:25:23',
                'updated_at' => '2023-10-09 05:53:32',
                'foto' => 'tZiBNdvmkihad2LbHdo6.JPG',
                'bidang_id' => NULL,
                'nip' => '197912242007012007',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 38,
                'name' => 'Kartinem',
                'jabatan' => 'PRANATA TEKNOLOGI INFORMASI KOMPUTER',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:25:59',
                'updated_at' => '2023-10-09 05:53:38',
                'foto' => 'xClj1E0FmgpomTNLrYnU.jpg',
                'bidang_id' => NULL,
                'nip' => '197203212007012010',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 39,
                'name' => 'Nurmiana Afriany S.T.',
                'jabatan' => 'CALON PERENCANA',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:26:06',
                'updated_at' => '2023-10-09 07:04:30',
                'foto' => '2uME06hhErz0bjcP93U3.jpg',
                'bidang_id' => NULL,
                'nip' => '198204122011012001',
                'golongan' => 'III/c',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => 'DINAS PENAnameN MODAL DAN PELAYANAN TERPADU SATU PINTU',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 40,
                'name' => 'Sri Hartati, S.Sos',
                'jabatan' => 'PENGADMINISTRASI KEUANGAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:26:47',
                'updated_at' => '2023-10-09 05:53:51',
                'foto' => '2qhy4MApaZS0zd9G3eII.jpg',
                'bidang_id' => NULL,
                'nip' => '197509132007012006',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 41,
                'name' => 'Stella Felicia Sinaga, S.Si.',
                'jabatan' => 'KEPALA SUB BAGIAN PERENCANAAN PROGRAM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:26:55',
                'updated_at' => '2023-10-11 06:26:40',
                'foto' => 'N1SmZsfiDdthzpGvA4ql.png',
                'bidang_id' => 1,
                'nip' => '199002262011012001',
                'golongan' => 'III/c',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => 3,
                'ketua_tim' => 'BIDANG CIPTA KARYA (PU), BIDANG JASA KONSTRUKSI (PU), SEKRETARIAT PU, DAN UPTD LABOLATORIUM (PU)',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 42,
                'name' => 'Ahmad Riyadi, S.Sos',
                'jabatan' => 'PENGADMINISTRASI SARANA DAN PRASARANA',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:27:33',
                'updated_at' => '2023-10-09 05:54:04',
                'foto' => 'okFFNsjgHFYuVzXo7Nv3.jpg',
                'bidang_id' => NULL,
                'nip' => '197806042007011009',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 44,
                'name' => 'Haris Amatiri',
                'jabatan' => 'PENGADMINISTRASI KEUANGAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:28:36',
                'updated_at' => '2023-10-09 05:54:16',
                'foto' => 'JXsih49FnsvPPbXgnbnP.jpg',
                'bidang_id' => NULL,
                'nip' => '197205242007011016',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 45,
                'name' => 'Kustaniah',
                'jabatan' => 'PENGADMINISTRASI KEUANGAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:29:31',
                'updated_at' => '2023-10-09 05:54:49',
                'foto' => 'UlKD2flCQne8nGpuSEVd.jpg',
                'bidang_id' => NULL,
                'nip' => '197608172007012019',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 47,
                'name' => 'Suwondo',
                'jabatan' => 'PENGADMINISTRASI PERENCANAAN DAN PROGRAM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:30:33',
                'updated_at' => '2023-10-09 05:54:40',
                'foto' => 'wyaHAganMBlYunvRtrLF.jpg',
                'bidang_id' => NULL,
                'nip' => '197404242007011025',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 49,
                'name' => 'Misbahul Jannah, S.Sos.',
                'jabatan' => 'PENGADMINISTRASI KEPEGAWAIAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:32:31',
                'updated_at' => '2023-10-09 05:54:30',
                'foto' => 'lvCawDkG8tCROUHPrTr6.jpg',
                'bidang_id' => NULL,
                'nip' => '197409012007012009',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 51,
                'name' => 'Kasim',
                'jabatan' => 'PENGADMINISTRASI UMUM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:33:19',
                'updated_at' => '2023-10-09 05:55:09',
                'foto' => '7glZFz3r5SoVk67kmrhH.jpg',
                'bidang_id' => NULL,
                'nip' => '197207082007011018',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 53,
                'name' => 'Suri Handayani, S.Sos.',
                'jabatan' => 'PENGADMINISTRASI UMUM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:33:55',
                'updated_at' => '2023-10-09 05:55:15',
                'foto' => 'XVM2odTwZFsIEAmw07rt.jpg',
                'bidang_id' => NULL,
                'nip' => '197409062007012015',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 54,
                'name' => 'Erika Wahyu Sartika',
                'jabatan' => 'PENGADMINISTRASI PERENCANAAN DAN PROGRAM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:34:30',
                'updated_at' => '2023-10-09 05:55:23',
                'foto' => '1ccM5kJPUnHB0c6XrTo1.JPG',
                'bidang_id' => NULL,
                'nip' => '197410272007012008',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 55,
                'name' => 'Ramlie',
                'jabatan' => 'PENGADMINISTRASI RUMAH TANGGA PRODUKSI',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:34:31',
                'updated_at' => '2023-10-09 05:52:40',
                'foto' => 'idFSajZpjTeHunF9g0sC.jpg',
                'bidang_id' => NULL,
                'nip' => '196705241988031005',
                'golongan' => 'III/b',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 56,
                'name' => 'H. Mukti Ali',
                'jabatan' => 'PENGADMINISTRASI PENERIMAAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:35:18',
                'updated_at' => '2023-10-09 05:52:04',
                'foto' => 'xr3do4HJcLAGh6jmd9eD.jpg',
                'bidang_id' => NULL,
                'nip' => '196806131993011002',
                'golongan' => 'III/b',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 57,
                'name' => 'Retno Sulistiyo, S.Sos.',
                'jabatan' => 'PENGADMINISTRASI KEPEGAWAIAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:35:21',
                'updated_at' => '2023-10-09 05:55:35',
                'foto' => '6h8MXeZL8rRIscOqRuQS.jpg',
                'bidang_id' => NULL,
                'nip' => '197511282007012010',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 58,
                'name' => 'Hendro Prowodadi',
                'jabatan' => 'PRANATA TEKNOLOGI INFORMASI KOMPUTER',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:35:54',
                'updated_at' => '2023-10-09 05:55:47',
                'foto' => 'nMfqs0RuB7szuKP08tMs.JPG',
                'bidang_id' => NULL,
                'nip' => '197602182007011008',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 59,
                'name' => 'Doney',
                'jabatan' => 'PENGADMINISTRASI UMUM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:36:54',
                'updated_at' => '2023-10-09 05:48:46',
                'foto' => 'UDuE1QvP2PxlHRJ0ZNYb.jpg',
                'bidang_id' => NULL,
                'nip' => '196812261993031010',
                'golongan' => 'III/b',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 60,
                'name' => 'Rahmat Hidayat',
                'jabatan' => 'PENGADMINISTRASI PERENCANAAN DAN PROGRAM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:37:45',
                'updated_at' => '2023-10-09 05:55:59',
                'foto' => 'pvh6tSJUoa2clpRcO2z0.jpg',
                'bidang_id' => NULL,
                'nip' => '197204152007011031',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 62,
                'name' => 'M. Agus Hendra, S.Sos.',
                'jabatan' => 'PENGADMINISTRASI KEPEGAWAIAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:38:39',
                'updated_at' => '2023-10-09 05:56:10',
                'foto' => '5T9AABuP0pGq7TyWGvO8.JPG',
                'bidang_id' => NULL,
                'nip' => '197712152007011017',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 63,
                'name' => 'Dwi Ery Mujahiddin  S.Hut.',
                'jabatan' => 'ANALIS PERENCANAAN STRATEGIS',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:39:15',
                'updated_at' => '2023-10-09 07:53:54',
                'foto' => 'Zdkp7CJ2YRjqwMftmcqh.jpg',
                'bidang_id' => NULL,
                'nip' => '197502052009011006',
                'golongan' => 'III/b',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => 'PENGENDALIAN, EVALUASI, DAN PELAPORAN',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 64,
                'name' => 'Nazly Nahdiar',
                'jabatan' => 'PENGADMINISTRASI PERENCANAAN DAN PROGRAM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:39:17',
                'updated_at' => '2023-10-09 05:46:46',
                'foto' => 'XD4oKctFwFWwPkV5NRVP.jpg',
                'bidang_id' => NULL,
                'nip' => '197904272008011016',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 65,
                'name' => 'Shinta Lakhsmi Sari',
                'jabatan' => 'PENGADMINISTRASI PERENCANAAN DAN PROGRAM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:40:11',
                'updated_at' => '2023-10-09 05:56:20',
                'foto' => 'Xf22luuFOD6YuYBCzhDF.jpg',
                'bidang_id' => NULL,
                'nip' => '197710252008012024',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 66,
                'name' => 'Fryma Putra Pratama S.T.',
                'jabatan' => 'CALON PERENCANA',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:40:16',
                'updated_at' => '2023-10-12 01:57:11',
                'foto' => 'mZ27KxBVE3R46Tk5HwVZ.png',
                'bidang_id' => NULL,
                'nip' => '198902162015031001',
                'golongan' => 'III/b',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 67,
                'name' => 'Efran S.E',
                'jabatan' => 'PENGOLAH DATA PENGANGGARAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:41:03',
                'updated_at' => '2023-10-09 05:48:59',
                'foto' => 'sntoj22SXLfLthiZE7WI.jpg',
                'bidang_id' => NULL,
                'nip' => '196603032001121003',
                'golongan' => 'III/b',
                'kelas_jabatan' => '6.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 68,
                'name' => 'Senindiyanto',
                'jabatan' => 'PENGADMINISTRASI PERSURATAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:41:25',
                'updated_at' => '2023-10-09 05:56:28',
                'foto' => 'RX1pD9ZvFvuYzLM6JTat.jpg',
                'bidang_id' => NULL,
                'nip' => '197504062008011016',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 69,
                'name' => 'Basri Saryati S.E.',
                'jabatan' => 'PENGELOLA KEGIATAN DAN ANGGARAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:41:55',
                'updated_at' => '2023-10-09 05:52:26',
                'foto' => 'Z9AU94CXTYN4iOtnYXeh.jpg',
                'bidang_id' => NULL,
                'nip' => '197211172007012006',
                'golongan' => 'III/b',
                'kelas_jabatan' => '6.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 70,
                'name' => 'Suherman',
                'jabatan' => 'PENGADMINISTRASI PERENCANAAN DAN PROGRAM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:41:59',
                'updated_at' => '2023-10-09 05:56:36',
                'foto' => '8jZFJeHRH8xQftqQ2H0a.jpeg',
                'bidang_id' => NULL,
                'nip' => '197805052008011028',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 71,
                'name' => 'Maretawiah Har',
                'jabatan' => 'PENGADMINISTRASI UMUM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:42:39',
                'updated_at' => '2023-10-09 05:56:45',
                'foto' => 'QQFEWv7PE4DgZBu7ZIrb.jpg',
                'bidang_id' => NULL,
                'nip' => '198003112008012022',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 72,
                'name' => 'Rudi Hertamiaji S.Sos.',
                'jabatan' => 'PENGADMINISTRASI PERENCANAAN DAN PROGRAM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:42:47',
                'updated_at' => '2023-10-09 05:48:28',
                'foto' => '3tdr3TkLqYK7HlFwkLvr.jpg',
                'bidang_id' => NULL,
                'nip' => '196802162007011015',
                'golongan' => 'III/b',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 73,
                'name' => 'Noordiansyah S.E.',
                'jabatan' => 'PENYUSUN RENCANA KEBUTUHAN SARANA DAN PRASARANA',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:43:36',
                'updated_at' => '2023-10-09 05:51:57',
                'foto' => 'pyl92iPGD5xwX1OoOmPv.jpg',
                'bidang_id' => NULL,
                'nip' => '197610152007011014',
                'golongan' => 'III/b',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 74,
                'name' => 'Darham',
                'jabatan' => 'PENGADMINISTRASI PERSURATAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:43:48',
                'updated_at' => '2023-10-09 05:56:55',
                'foto' => 'YAzEJrFodRSREDR9ba5i.jpg',
                'bidang_id' => NULL,
                'nip' => '196808122009011001',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 75,
                'name' => 'Ardiansyah',
                'jabatan' => 'PRANATA TEKNOLOGI INFORMASI KOMPUTER',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:44:36',
                'updated_at' => '2023-10-09 05:57:03',
                'foto' => 'Q7BqR9sAYmoJJjFekIfb.jpg',
                'bidang_id' => NULL,
                'nip' => '197602212009011002',
                'golongan' => 'II/d',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 76,
                'name' => 'Astien Ariyani  S.E.',
                'jabatan' => 'ANALIS PERENCANAAN ANGGARAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:44:51',
                'updated_at' => '2023-10-09 07:12:22',
                'foto' => 'G3uBUPvejZlu9oM8Lz0J.JPG',
                'bidang_id' => NULL,
                'nip' => '198111302009012002',
                'golongan' => 'III/b',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => 'DINAS PEMBERDAYAAN MASYARAKAT DAN PEMERINTAHAN DESA, DAN DINAS KEPENDUDUKAN PEMBERDAYAAN PEREMPUAN DAN PERLINDUNGAN ANAK',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 77,
                'name' => 'Tabrani .A',
                'jabatan' => 'PENGADMINISTRASI UMUM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:45:22',
                'updated_at' => '2023-10-09 05:53:15',
                'foto' => 'ephD06mO2g1CIdmmh5ae.jpg',
                'bidang_id' => NULL,
                'nip' => '197708132014061002',
                'golongan' => 'II/b',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 79,
                'name' => 'Rusman',
                'jabatan' => 'PENGADMINISTRASI UMUM',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:46:02',
                'updated_at' => '2023-10-09 05:49:43',
                'foto' => 'w7hcPSnlW4HMwkG2ItVf.jpg',
                'bidang_id' => NULL,
                'nip' => '197908042014061001',
                'golongan' => 'II/b',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 80,
                'name' => 'Farisa S.E.',
                'jabatan' => 'PENATA LAPORAN KEUANGAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:46:40',
                'updated_at' => '2023-10-09 05:50:27',
                'foto' => 'cWE5o3gDcyGbvdmUPWvy.jpg',
                'bidang_id' => NULL,
                'nip' => '197112162002122005',
                'golongan' => 'III/b',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 82,
                'name' => 'Sukandar S.Sos.',
                'jabatan' => 'ANALIS PEMERINTAHAN UMUM DAN OTONOMI DAERAH',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:47:22',
                'updated_at' => '2023-10-09 07:50:25',
                'foto' => '9Mm7zkexJaaa4c3ESswO.jpg',
                'bidang_id' => NULL,
                'nip' => '196903312007011013',
                'golongan' => 'III/b',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => 'BADAN PERENCANAAN PEMBANGUNAN DAERAH, DAN INSPEKTORAT WILAYAH',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 83,
                'name' => 'Slamet Hariyanto A.Md.',
                'jabatan' => 'PENGELOLA KEUANGAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:48:04',
                'updated_at' => '2023-10-09 05:49:10',
                'foto' => 'md9F8OqKCck77jHfEJsU.jpg',
                'bidang_id' => NULL,
                'nip' => '198306292009031003',
                'golongan' => 'III/b',
                'kelas_jabatan' => '6.C',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 84,
                'name' => 'M . Yazid',
                'jabatan' => 'PENGADMINISTRASI ANGGARAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:48:47',
                'updated_at' => '2023-10-09 05:52:49',
                'foto' => 'pROX1IEdC1hjFy9jnRXn.jpg',
                'bidang_id' => NULL,
                'nip' => '196509041986011002',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 85,
                'name' => 'Mico Iswawan',
                'jabatan' => 'PRANATA TEKNOLOGI INFORMASI KOMPUTER',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:48:51',
                'updated_at' => '2023-10-09 05:50:13',
                'foto' => '323hlctWQLE6wsJqgK1T.jpg',
                'bidang_id' => NULL,
                'nip' => '197110202009011001',
                'golongan' => 'II/b',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 86,
                'name' => 'Ali Mudzakkir Hamidi S.STP',
                'jabatan' => 'ANALIS PENGEMBANGAN WILAYAH',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:49:48',
                'updated_at' => '2023-10-09 07:49:04',
                'foto' => '1wuL90FoEyqLckQeJqAU.jpg',
                'bidang_id' => NULL,
                'nip' => '199509042017081001',
                'golongan' => 'III/b',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => 'SEKRETARIAT DAERAH, DAN BADAN KESATUAN BANGSA DAN POLITIK',
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 87,
                'name' => 'Irwansyah',
                'jabatan' => 'PENGADMINISTRASI TEKNIS PEMERIKSAAN DAN PERAWATAN KENDARAAN BERMOTOR',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:50:20',
                'updated_at' => '2023-10-09 05:46:54',
                'foto' => 'wCYphVHcHPvJQsbn3BZ7.jpg',
                'bidang_id' => NULL,
                'nip' => '196703072007011020',
                'golongan' => 'II/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 88,
                'name' => 'Hastati Paturusi S.H.',
                'jabatan' => 'ARSIPARIS AHLI PERTAMA',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:50:48',
                'updated_at' => '2023-10-09 05:49:35',
                'foto' => 'dBZfg8O9WlQE4WC08dU5.jpg',
                'bidang_id' => NULL,
                'nip' => '197910222008012020',
                'golongan' => 'III/a',
                'kelas_jabatan' => '7.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 89,
                'name' => 'Yunan Junaidi',
                'jabatan' => 'PRAMU BAKTI',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:51:03',
                'updated_at' => '2023-10-09 05:50:07',
                'foto' => 'dWvc5u6z7IeWbtIkrjtE.jpg',
                'bidang_id' => NULL,
                'nip' => '197003152008011014',
                'golongan' => 'I/d',
                'kelas_jabatan' => '1.A',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 90,
                'name' => 'Yasin Purnomo',
                'jabatan' => 'PRAMU BAKTI',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:51:36',
                'updated_at' => '2023-10-09 05:48:09',
                'foto' => 'HEjW5uJ45t0Y4RpvH8KB.jpg',
                'bidang_id' => NULL,
                'nip' => '198503232010011002',
                'golongan' => 'I/c',
                'kelas_jabatan' => '1.A',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 91,
                'name' => 'Muhammad Hendra Wahyudi',
                'jabatan' => 'PENGADMINISTRASI SARANA DAN PRASARANA',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:52:12',
                'updated_at' => '2023-10-09 05:47:27',
                'foto' => 'TbX4hPxqXKIrAYPie5RE.jpg',
                'bidang_id' => NULL,
                'nip' => '197710312002121005',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 92,
                'name' => 'Aseri',
                'jabatan' => 'PENGADMINISTRASI PERSURATAN',
                'status_aktif' => 1,
                'created_at' => '2021-03-14 23:53:16',
                'updated_at' => '2023-10-09 05:48:18',
                'foto' => 'qcNejEigstLzG0kmHKqA.JPG',
                'bidang_id' => NULL,
                'nip' => '196805142000121001',
                'golongan' => 'III/a',
                'kelas_jabatan' => '5.B',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 95,
                'name' => 'Idham Rahma Putra, S.T.',
                'jabatan' => 'SURVEYOR PEMETAAN AHLI PERTAMA',
                'status_aktif' => 1,
                'created_at' => '2022-01-24 07:04:31',
                'updated_at' => '2023-10-12 01:56:45',
                'foto' => 'sKAU2muT5zmk9TqTzXVc.png',
                'bidang_id' => NULL,
                'nip' => '198605302015031001',
                'golongan' => 'III/b',
                'kelas_jabatan' => '8.A',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => '0',
                'urutan_jabatan' => NULL,
                'ketua_tim' => NULL,
                'slug' => Str::slug(Str::random(10)),
            ],
            [
                'id' => 96,
                'name' => 'Angki Setyadarma, S.STP',
                'jabatan' => 'PENYUSUN RENCANA SARANA PENGEMBANGAN USAHA',
                'status_aktif' => 1,
                'created_at' => '2022-01-24 07:07:24',
                'updated_at' => '2023-10-12 01:56:22',
                'foto' => 'w1ywXtck7g7R4CGqMmup.png',
                'bidang_id' => NULL,
                'nip' => '199508232017081002',
                'golongan' => 'III/a',
                'kelas_jabatan' => '-',
                'status_jabatan' => 'Non Pejabat',
                'status_kehadiran' => 'Hadir',
                'urutan_jabatan' => NULL,
                'ketua_tim' => 'BADAN PENGELOLAAN KEUANGAN DAN ASET DAERAH, DAN BADAN PENDAPATAN DAERAH',
                'slug' => Str::slug(Str::random(10)),
            ],
        );
    }
}
