<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class WelcomeSliderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table("welcome_sliders")->insert([
            [
                'id' => 25,
                'title' => 'PPID Bappeda Prov Kaltim',
                'active' => 0,
                'created_at' => '2021-10-28 03:12:31',
                'updated_at' => '2023-11-02 00:58:30',
                'image' => 'PHBX1Jk8ZewXMzQXUr0F.jpg',
                'orders' => 9,
                'slug' => 'ppid-bappeda-prov-kaltim',
            ],
            [
                'id' => 26,
                'title' => 'Bappeda Pedia',
                'active' => 0,
                'created_at' => '2021-10-28 03:12:54',
                'updated_at' => '2023-11-02 00:59:29',
                'image' => 'fZEA78B6B2nexHjp3UQQ.jpg',
                'orders' => 8,
                'slug' => 'bappeda-pedia',
            ],
            [
                'id' => 27,
                'title' => 'Maklumat Pelayanan',
                'active' => 0,
                'created_at' => '2021-10-28 03:51:39',
                'updated_at' => '2024-09-23 06:26:24',
                'image' => 'HR8Gp4Bw8nHWzNbwPBSA.jpg',
                'orders' => 4,
                'slug' => 'maklumat-pelayanan',
            ],
            [
                'id' => 28,
                'title' => 'Janji Pelayanan',
                'active' => 0,
                'created_at' => '2021-10-28 03:52:05',
                'updated_at' => '2024-09-23 08:41:52',
                'image' => 'SPuGeJAueUIIUlJ3OVk3.jpg',
                'orders' => 5,
                'slug' => 'janji-pelayanan',
            ],
            [
                'id' => 29,
                'title' => 'Motto Pelayanan',
                'active' => 0,
                'created_at' => '2021-10-28 03:52:25',
                'updated_at' => '2024-09-23 05:38:30',
                'image' => '2QmRI2CNmd0WW6PsBYB6.jpg',
                'orders' => 7,
                'slug' => 'motto-pelayanan',
            ],
            [
                'id' => 30,
                'title' => 'Pustaka Bappeda Kaltim',
                'active' => 0,
                'created_at' => '2021-10-28 04:22:45',
                'updated_at' => '2023-11-02 00:59:36',
                'image' => '3JXjYsrPrmVrMrTHvBA9.jpg',
                'orders' => 10,
                'slug' => 'pustaka-bappeda-kaltim',
            ],
            [
                'id' => 31,
                'title' => 'Hubungi Kami',
                'active' => 0,
                'created_at' => '2021-10-28 08:14:19',
                'updated_at' => '2024-09-24 01:50:37',
                'image' => 'ri5fqhI5pW5xffsrge68.jpg',
                'orders' => 3,
                'slug' => 'hubungi-kami',
            ],
            [
                'id' => 32,
                'title' => 'Survey Kepuasan Masyarakat (SKM)',
                'active' => 0,
                'created_at' => '2021-10-28 08:40:47',
                'updated_at' => '2023-12-20 01:57:35',
                'image' => 'fMdwTd8XB6qAQwyR3BrD.png',
                'orders' => 1,
                'slug' => 'survey-kepuasan-masyarakat-skm',
            ],
            [
                'id' => 33,
                'title' => 'Biaya Tarif Layanan',
                'active' => 0,
                'created_at' => '2021-10-29 04:28:53',
                'updated_at' => '2024-09-24 09:16:30',
                'image' => 'LYCWR8JoDvsqzPHl7eeG.jpg',
                'orders' => 9,
                'slug' => 'biaya-tarif-layanan',
            ],
            [
                'id' => 34,
                'title' => 'Spanduk Bersama Melawan Korupsi',
                'active' => 0,
                'created_at' => '2022-03-22 09:47:54',
                'updated_at' => '2024-09-24 02:37:11',
                'image' => 'Ju0W5CwVB9G102ZL7mCm.png',
                'orders' => 6,
                'slug' => 'spanduk-bersama-melawan-korupsi',
            ],
            [
                'id' => 37,
                'title' => 'Survei Penyusunan RPJPD Kaltim 2025-2045',
                'active' => 0,
                'created_at' => '2023-11-02 00:25:23',
                'updated_at' => '2023-12-19 04:03:28',
                'image' => 'HbHmdv5D9pORgdJDm1cS.jpg',
                'orders' => 1,
                'slug' => 'survei-penyusunan-rpjpd-kaltim-2025-2045',
            ],
            [
                'id' => 39,
                'title' => 'Survey Kepuasan Masyarakat (SKM)',
                'active' => 0,
                'created_at' => '2023-12-20 02:15:54',
                'updated_at' => '2024-10-17 11:18:40',
                'image' => 'Cmwan7ExuG5YmYg6PZBu.png',
                'orders' => 1,
                'slug' => 'survey-kepuasan-masyarakat-skm',
            ],
            [
                'id' => 40,
                'title' => 'Motto Pelayanan',
                'active' => 0,
                'created_at' => '2024-09-23 01:21:14',
                'updated_at' => '2024-10-17 11:21:07',
                'image' => 'Z1JMDzFzyynXzM22CIta.png',
                'orders' => 7,
                'slug' => 'motto-pelayanan',
            ],
            [
                'id' => 41,
                'title' => 'Membangun Kaltim Untuk Nusantara',
                'active' => 0,
                'created_at' => '2024-09-23 05:39:25',
                'updated_at' => '2024-10-17 11:18:46',
                'image' => 'vICzlmWUV8bnBX4OOIxP.png',
                'orders' => 2,
                'slug' => 'membangun-kaltim-untuk-nusantara',
            ],
            [
                'id' => 42,
                'title' => 'Maklumat Pelayanan',
                'active' => 0,
                'created_at' => '2024-09-23 06:26:34',
                'updated_at' => '2024-10-17 11:20:16',
                'image' => 'bKAHnstLZFwMvCL5H6jx.png',
                'orders' => 5,
                'slug' => 'maklumat-pelayanan',
            ],
            [
                'id' => 43,
                'title' => 'Janji Pelayanan',
                'active' => 0,
                'created_at' => '2024-09-23 08:42:05',
                'updated_at' => '2024-10-17 11:20:36',
                'image' => 'futcn04TTrA2g5S8aI0U.png',
                'orders' => 6,
                'slug' => 'janji-pelayanan',
            ],
            [
                'id' => 44,
                'title' => 'Informasi Layanan',
                'active' => 0,
                'created_at' => '2024-09-24 01:50:51',
                'updated_at' => '2024-10-17 11:18:51',
                'image' => 'DPmzNZayCV8QIw6B1a08.png',
                'orders' => 3,
                'slug' => 'informasi-layanan',
            ],
            [
                'id' => 45,
                'title' => 'Hakordia 2023',
                'active' => 0,
                'created_at' => '2024-09-24 02:38:13',
                'updated_at' => '2024-10-17 11:19:48',
                'image' => 'uquPJxIOwnlcLmfUVYZM.png',
                'orders' => 4,
                'slug' => 'hakordia-2023',
            ],
            [
                'id' => 46,
                'title' => 'Biaya Tarif Layanan',
                'active' => 0,
                'created_at' => '2024-09-24 09:16:42',
                'updated_at' => '2024-10-17 11:21:16',
                'image' => 'DWyozHwCoA7zEvPb5r9w.png',
                'orders' => 8,
                'slug' => 'biaya-tarif-layanan',
            ],
            [
                'id' => 47,
                'title' => 'Survey Kepuasan Masyarakat (SKM)',
                'active' => 1,
                'created_at' => '2024-10-17 00:23:02',
                'updated_at' => '2024-10-17 11:19:02',
                'image' => 'B0PjjcakoCOfaSt2AvrB.png',
                'orders' => 1,
                'slug' => 'survey-kepuasan-masyarakat-skm',
            ],
            [
                'id' => 48,
                'title' => 'Membangun Kaltim Untuk Nusantara',
                'active' => 1,
                'created_at' => '2024-10-17 00:23:17',
                'updated_at' => '2024-10-17 11:19:15',
                'image' => 'YV8XVzihTN5zx0ai0QjQ.png',
                'orders' => 2,
                'slug' => 'membangun-kaltim-untuk-nusantara',
            ],
            [
                'id' => 49,
                'title' => 'Informasi Layanan',
                'active' => 1,
                'created_at' => '2024-10-17 00:23:37',
                'updated_at' => '2024-10-17 11:19:20',
                'image' => 'FkcESHhXzw6aIbFdpWBx.png',
                'orders' => 3,
                'slug' => 'informasi-layanan',
            ],
            [
                'id' => 50,
                'title' => 'Hakordia 2023',
                'active' => 1,
                'created_at' => '2024-10-17 00:24:06',
                'updated_at' => '2024-10-17 11:19:57',
                'image' => '8HA6QPvJ8ssMUa43wcOf.png',
                'orders' => 4,
                'slug' => 'hakordia-2023',
            ],
            [
                'id' => 51,
                'title' => 'Maklumat Pelayanan',
                'active' => 1,
                'created_at' => '2024-10-17 00:24:37',
                'updated_at' => '2024-10-17 11:20:09',
                'image' => '5Z5Hlm0fMTsCrUvHzivf.png',
                'orders' => 5,
                'slug' => 'maklumat-pelayanan',
            ],
            [
                'id' => 52,
                'title' => 'Janji Pelayanan',
                'active' => 1,
                'created_at' => '2024-10-17 00:25:03',
                'updated_at' => '2024-10-17 11:20:29',
                'image' => '3DRoxnZY7kntqasEh99L.png',
                'orders' => 6,
                'slug' => 'janji-pelayanan',
            ],
            [
                'id' => 53,
                'title' => 'Biaya Tarif Layanan',
                'active' => 1,
                'created_at' => '2024-10-17 00:26:04',
                'updated_at' => '2024-10-17 11:21:24',
                'image' => '1q7lnJhHOlAsgp0lKluu.png',
                'orders' => 8,
                'slug' => 'biaya-tarif-layanan',
            ],
            [
                'id' => 54,
                'title' => 'Moto Pelayanan',
                'active' => 1,
                'created_at' => '2024-10-17 00:26:27',
                'updated_at' => '2024-10-17 11:21:01',
                'image' => 'vF2gfLnFh8P9EXj518sC.png',
                'orders' => 7,
                'slug' => 'moto-pelayanan',
            ],
        ]);
    }
}
